INSERT INTO `Item` (`minecraftId`, `asset`, `name`) VALUES
('minecraft:stone', 'vanilla/stone.webp', 'Stone'),
('minecraft:granite', 'vanilla/granite.webp', 'Granite'),
('minecraft:polished_granite', 'vanilla/polished_granite.webp', 'Polished Granite'),
('minecraft:diorite', 'vanilla/diorite.webp', 'Diorite'),
('minecraft:polished_diorite', 'vanilla/polished_diorite.webp', 'Polished Diorite'),
('minecraft:andesite', 'vanilla/andesite.webp', 'Andesite'),
('minecraft:polished_andesite', 'vanilla/polished_andesite.webp', 'Polishe Andesite'),
('minecraft:grass_block', 'vanilla/grass_block.webp', 'Grass Block'),
('minecraft:dirt', 'vanilla/dirt.webp', 'Dirt'),
('minecraft:coarse_dirt', 'vanilla/coarse_dirt.webp', 'Coarse Dirt'),
('minecraft:podzol', 'vanilla/podzol.webp', 'Podzol'),
('minecraft:crimson_nylium', 'vanilla/crimson_nylium.webp', 'Crimson Nylium'),
('minecraft:warped_nylium', 'vanilla/warped_nylium.webp', 'Warped Nylium'),
('minecraft:cobblestone', 'vanilla/cobblestone.webp', 'Cobblestone'),
('minecraft:oak_planks', 'vanilla/oak_planks.webp', 'Oak Planks'),
('minecraft:spruce_planks', 'vanilla/spruce_planks.webp', 'Spruce Planks'),
('minecraft:birch_planks', 'vanilla/birch_planks.webp', 'Birch Planks'),
('minecraft:jungle_planks', 'vanilla/jungle_planks.webp', 'Jungle Planks'),
('minecraft:acacia_planks', 'vanilla/acacia_planks.webp', 'Acacia Planks'),
('minecraft:dark_oak_planks', 'vanilla/dark_oak_planks.webp', 'Dark oak Planks'),
('minecraft:crimson_planks', 'vanilla/crimson_planks.webp', 'Crimson Planks'),
('minecraft:warped_planks', 'vanilla/warped_planks.webp', 'Warped Planks'),
('minecraft:bedrock', 'vanilla/bedrock.webp', 'Bedrock'),
('minecraft:sand', 'vanilla/sand.webp', 'Sand'),
('minecraft:red_sand', 'vanilla/red_sand.webp', 'Red sand'),
('minecraft:gravel', 'vanilla/gravel.webp', 'Gravel'),
('minecraft:gold_ore', 'vanilla/gold_ore.webp', 'Gold ore'),
('minecraft:iron_ore', 'vanilla/iron_ore.webp', 'Iron ore'),
('minecraft:coal_ore', 'vanilla/coal_ore.webp', 'Coal ore'),
('minecraft:nether_gold_ore', 'vanilla/nether_gold_ore.webp', 'Nether Gold Ore'),
('minecraft:oak_log', 'vanilla/oak_log.webp', 'Oak Log'),
('minecraft:spruce_log', 'vanilla/spruce_log.webp', 'Spruce Log'),
('minecraft:birch_log', 'vanilla/birch_log.webp', 'Birch Log'),
('minecraft:jungle_log', 'vanilla/jungle_log.webp', 'Jungle Log'),
('minecraft:acacia_log', 'vanilla/acacia_log.webp', 'Acacia Log'),
('minecraft:dark_oak_log', 'vanilla/dark_oak_log.webp', 'Dark oak Log'),
('minecraft:crimson_stem', 'vanilla/crimson_stem.gif', 'Crimson Stem'),
('minecraft:warped_stem', 'vanilla/warped_stem.gif', 'Warped Stem'),
('minecraft:stripped_oak_log', 'vanilla/oak_stripped_log.webp', 'Stripped Oak Log'),
('minecraft:stripped_spruce_log', 'vanilla/spruce_stripped_log.webp', 'Stripped Spruce Log'),
('minecraft:stripped_birch_log', 'vanilla/birch_stripped_log.webp', 'Stripped Birch Log'),
('minecraft:stripped_jungle_log', 'vanilla/jungle_stripped_log.webp', 'Stripped Jungle Log'),
('minecraft:stripped_acacia_log', 'vanilla/acacia_stripped_log.webp', 'Stripped Acacia Log'),
('minecraft:stripped_dark_oak_log', 'vanilla/dark_oak_stripped_log.webp', 'Stripped Dark Oak Log'),
('minecraft:stripped_crimson_stem', 'vanilla/crimson_stripped_stem.webp', 'Stripped Crimson Stem'),
('minecraft:stripped_warped_stem', 'vanilla/warped_stripped_stem.webp', 'Stripped Warped Stem'),
('minecraft:oak_wood', 'vanilla/oak_wood.webp', 'Oak Wood'),
('minecraft:spruce_wood', 'vanilla/spruce_wood.webp', 'Spruce Wood'),
('minecraft:birch_wood', 'vanilla/birch_wood.webp', 'Birch Wood'),
('minecraft:jungle_wood', 'vanilla/jungle_wood.webp', 'Jungle Wood'),
('minecraft:acacia_wood', 'vanilla/acacia_wood.webp', 'Acacia Wood'),
('minecraft:dark_oak_wood', 'vanilla/dark_oak_wood.webp', 'Dark oak Wood'),
('minecraft:crimson_hyphae', 'vanilla/crimson_hyphae.gif', 'Crimson Hyphae'),
('minecraft:warped_hyphae', 'vanilla/warped_hyphae.gif', 'Warped Hyphae'),
('minecraft:sponge', 'vanilla/sponge.webp', 'Sponge'),
('minecraft:wet_sponge', 'vanilla/wet_sponge.webp', 'Wet Sponge'),
('minecraft:glass', 'vanilla/glass.webp', 'Glass'),
('minecraft:lapis_ore', 'vanilla/lapis_ore.webp', 'Lapis Ore'),
('minecraft:lapis_block', 'vanilla/lapis_block.webp', 'Lapis Block'),
('minecraft:sandstone', 'vanilla/sandstone.webp', 'Sandstone'),
('minecraft:chiseled_sandstone', 'vanilla/chiseled_sandstone.webp', 'Chiseled Sandstone'),
('minecraft:cut_sandstone', 'vanilla/cut_sandstone.webp', 'Cut Sandstone'),
('minecraft:white_wool', 'vanilla/white_wool.webp', 'White Wool'),
('minecraft:orange_wool', 'vanilla/orange_wool.webp', 'Orange Wool'),
('minecraft:magenta_wool', 'vanilla/magenta_wool.webp', 'Magenta Wool'),
('minecraft:light_blue_wool', 'vanilla/light_blue_wool.webp', 'Light Blue Wool'),
('minecraft:yellow_wool', 'vanilla/yellow_wool.webp', 'Yellow Wool'),
('minecraft:lime_wool', 'vanilla/lime_wool.webp', 'lime Wool'),
('minecraft:pink_wool', 'vanilla/pink_wool.webp', 'Pink Wool'),
('minecraft:gray_wool', 'vanilla/gray_wool.webp', 'Gray Wool'),
('minecraft:light_gray_wool', 'vanilla/light_gray_wool.webp', 'Light Gray Wool'),
('minecraft:cyan_wool', 'vanilla/cyan_wool.webp', 'Cyan Wool'),
('minecraft:purple_wool', 'vanilla/purple_wool.webp', 'Purple Wool'),
('minecraft:blue_wool', 'vanilla/blue_wool.webp', 'Blue Wool'),
('minecraft:brown_wool', 'vanilla/brown_wool.webp', 'Brown Wool'),
('minecraft:green_wool', 'vanilla/green_wool.webp', 'Green Wool'),
('minecraft:red_wool', 'vanilla/red_wool.webp', 'Red Wool'),
('minecraft:black_wool', 'vanilla/black_wool.webp', 'Black Wool'),
('minecraft:gold_block', 'vanilla/gold_block.webp', 'Gold Block'),
('minecraft:iron_block', 'vanilla/iron_block.webp', 'Iron Block'),
('minecraft:oak_slab', 'vanilla/oak_slab.webp', 'Oak Slab'),
('minecraft:spruce_slab', 'vanilla/spruce_slab.webp', 'Spruce Slab'),
('minecraft:birch_slab', 'vanilla/birch_slab.webp', 'Birch Slab'),
('minecraft:jungle_slab', 'vanilla/jungle_slab.webp', 'Jungle Slab'),
('minecraft:acacia_slab', 'vanilla/acacia_slab.webp', 'Acacia Slab'),
('minecraft:dark_oak_slab', 'vanilla/dark_oak_slab.webp', 'Dark oak Slab'),
('minecraft:crimson_slab', 'vanilla/crimson_slab.webp', 'Crimson Slab'),
('minecraft:warped_slab', 'vanilla/warped_slab.webp', 'Warped Slab'),
('minecraft:stone_slab', 'vanilla/stone_slab.webp', 'Stone Slab'),
('minecraft:smooth_stone_slab', 'vanilla/smooth_stone_slab.webp', 'Smooth Stone Slab'),
('minecraft:sandstone_slab', 'vanilla/sandstone_slab.webp', 'Sandstone Slab'),
('minecraft:cut_sandstone_slab', 'vanilla/cut_sandstone_slab.webp', 'Cut Sandstone Slab'),
('minecraft:petrified_oak_slab', 'vanilla/petrified_oak_slab.webp', 'Petrified Oak Slab'),
('minecraft:cobblestone_slab', 'vanilla/cobblestone_slab.webp', 'Cobblestone Slab'),
('minecraft:brick_slab', 'vanilla/brick_slab.webp', 'Brick Slab'),
('minecraft:stone_brick_slab', 'vanilla/stone_brick_slab.webp', 'Stone Brick Slab'),
('minecraft:nether_brick_slab', 'vanilla/nether_brick_slab.webp', 'Nether Brick Slab'),
('minecraft:quartz_slab', 'vanilla/quartz_slab.webp', 'Quartz Slab'),
('minecraft:red_sandstone_slab', 'vanilla/red_sandstone_slab.webp', 'Red Sandstone Slab'),
('minecraft:cut_red_sandstone_slab', 'vanilla/cut_red_sandstone_slab.webp', 'Cut Red Sandstone Slab'),
('minecraft:purpur_slab', 'vanilla/purpur_slab.webp', 'Purpur Slab'),
('minecraft:prismarine_slab', 'vanilla/prismarine_slab.webp', 'Prismarine Slab'),
('minecraft:prismarine_brick_slab', 'vanilla/prismarine_brick_slab.webp', 'Prismarine Brick Slab'),
('minecraft:dark_prismarine_slab', 'vanilla/dark_prismarine_slab.webp', 'Dark Prismarine Slab'),
('minecraft:smooth_quartz', 'vanilla/smooth_quartz.webp', 'Smooth Quartz'),
('minecraft:smooth_red_sandstone', 'vanilla/smooth_red_sandstone.webp', 'Smooth Red Sandstone'),
('minecraft:smooth_sandstone', 'vanilla/smooth_sandstone.webp', 'Smooth Sandstone'),
('minecraft:smooth_stone', 'vanilla/smooth_stone.webp', 'Smooth Stone'),
('minecraft:bricks', 'vanilla/bricks.webp', 'Bricks'),
('minecraft:bookshelf', 'vanilla/bookshelf.webp', 'Bookshelf'),
('minecraft:mossy_cobblestone', 'vanilla/mossy_cobblestone.webp', 'Mossy Cobblestone'),
('minecraft:obsidian', 'vanilla/obsidian.webp', 'Obsidian'),
('minecraft:pupur_block', 'vanilla/pupur_block.webp', 'Pupur Block'),
('minecraft:purpur_pillar', 'vanilla/purpur_pillar.webp', 'Purpur Pillar'),
('minecraft:oak_stairs', 'vanilla/oak_stairs.webp', 'Oak Stairs'),
('minecraft:diamond_ore', 'vanilla/diamond_ore.webp', 'Diamond Ore'),
('minecraft:diamond_block', 'vanilla/diamond_block.webp', 'Diamond Block'),
('minecraft:cobblestone_stairs', 'vanilla/cobblestone_stairs.webp', 'Cobblestone Stairs'),
('minecraft:redstone_ore', 'vanilla/redstone_ore.webp', 'Redstone Ore'),
('minecraft:ice', 'vanilla/ice.webp', 'Ice'),
('minecraft:snow_block', 'vanilla/snow_block.webp', 'Snow Block'),
('minecraft:clay', 'vanilla/clay.webp', 'Clay'),
('minecraft:pumpkin', 'vanilla/pumpkin.webp', 'Pumpkin'),
('minecraft:carved_pumpkin', 'vanilla/carved_pumpkin.webp', 'Carved Pumpkin'),
('minecraft:netherrack', 'vanilla/netherrack.webp', 'Netherrack'),
('minecraft:soul_sand', 'vanilla/soul_sand.webp', 'Soul Sand'),
('minecraft:soul_soil', 'vanilla/soul_soil.webp', 'Soul Soil'),
('minecraft:basalt', 'vanilla/basalt.webp', 'Basalt'),
('minecraft:polished_basalt', 'vanilla/polished_basalt.webp', 'Polished Basalt'),
('minecraft:glowstone', 'vanilla/glowstone.webp', 'Glowstone'),
('minecraft:jack_o_lantern', 'vanilla/jack_o_lantern.webp', 'Jack o Lantern'),
('minecraft:stone_bricks', 'vanilla/stone_bricks.webp', 'Stone Bricks'),
('minecraft:mossy_stone_bricks', 'vanilla/mossy_stone_bricks.webp', 'Mossy Stone Bricks'),
('minecraft:cracked_stone_bricks', 'vanilla/cracked_stone_bricks.webp', 'Cracked Stone Bricks'),
('minecraft:chiseled_stone_bricks', 'vanilla/chiseled_stone_bricks.webp', 'Chiseled Stone Bricks'),
('minecraft:melon', 'vanilla/melon.webp', 'Melon'),
('minecraft:brick_stairs', 'vanilla/brick_stairs.webp', 'Brick Stairs'),
('minecraft:stone_brick_stairs', 'vanilla/stone_brick_stairs.webp', 'Stone Brick Stairs'),
('minecraft:mycelium', 'vanilla/mycelium.webp', 'Mycelium'),
('minecraft:nether_bricks', 'vanilla/nether_bricks.webp', 'Nether Bricks'),
('minecraft:cracked_nether_bricks', 'vanilla/cracked_nether_bricks.webp', 'Cracked Nether Bricks'),
('minecraft:chiseled_nether_bricks', 'vanilla/chiseled_nether_bricks.webp', 'Chiseled Nether Bricks'),
('minecraft:nether_brick_stairs', 'vanilla/nether_brick_stairs.webp', 'Nether Brick Stairs'),
('minecraft:end_stone', 'vanilla/end_stone.webp', 'End Stone'),
('minecraft:end_stone_bricks', 'vanilla/end_stone_bricks.webp', 'End Stone Bricks'),
('minecraft:sandstone_stairs', 'vanilla/sandstone_stairs.webp', 'Sandstone Stairs'),
('minecraft:emerald_ore', 'vanilla/emerald_ore.webp', 'Emerald Ore'),
('minecraft:emerald_block', 'vanilla/emerald_block.webp', 'Block Of Emerald'),
('minecraft:spruce_stairs', 'vanilla/spruce_stairs.webp', 'Spruce Stairs'),
('minecraft:birch_stairs', 'vanilla/birch_stairs.webp', 'Birch Stairs'),
('minecraft:jungle_stairs', 'vanilla/jungle_stairs.webp', 'Jungle Stairs'),
('minecraft:crimson_stairs', 'vanilla/crimson_stairs.webp', 'Crimson Stairs'),
('minecraft:warped_stairs', 'vanilla/warped_stairs.webp', 'Warped Stairs'),
('minecraft:nether_quartz_ore', 'vanilla/nether_quartz_ore.webp', 'Nether Quartz Ore'),
('minecraft:chiseled_quartz_block', 'vanilla/chiseled_quartz_block.webp', 'Chiseled Quartz Block'),
('minecraft:quartz_block', 'vanilla/quartz_block.webp', 'Quartz Block'),
('minecraft:quartz_bricks', 'vanilla/quartz_bricks.webp', 'Quartz Bricks'),
('minecraft:quartz_pillar', 'vanilla/quartz_pillar.webp', 'Quartz Pillar'),
('minecraft:quartz_stairs', 'vanilla/quartz_stairs.webp', 'Quartz Stairs'),
('minecraft:white_terracotta', 'vanilla/white_terracotta.webp', 'white Terracotta'),
('minecraft:orange_terracotta', 'vanilla/orange_terracotta.webp', 'Orange Terracotta'),
('minecraft:magenta_terracotta', 'vanilla/magenta_terracotta.webp', 'Magenta Terracotta'),
('minecraft:light_blue_terracotta', 'vanilla/light_blue_terracotta.webp', 'Light Blue Terracotta'),
('minecraft:yellow_terracotta', 'vanilla/yellow_terracotta.webp', 'Yellow Terracotta'),
('minecraft:lime_terracotta', 'vanilla/lime_terracotta.webp', 'lime Terracotta'),
('minecraft:pink_terracotta', 'vanilla/pink_terracotta.webp', 'Pink Terracotta'),
('minecraft:gray_terracotta', 'vanilla/gray_terracotta.webp', 'Gray Terracotta'),
('minecraft:light_gray_terracotta', 'vanilla/light_gray_terracotta.webp', 'Light Gray Terracotta'),
('minecraft:cyan_terracotta', 'vanilla/cyan_terracotta.webp', 'Cyan Terracotta'),
('minecraft:purple_terracotta', 'vanilla/purple_terracotta.webp', 'Purple Terracotta'),
('minecraft:blue_terracotta', 'vanilla/blue_terracotta.webp', 'Blue Terracotta'),
('minecraft:brown_terracotta', 'vanilla/brown_terracotta.webp', 'Brown Terracotta'),
('minecraft:green_terracotta', 'vanilla/green_terracotta.webp', 'Green Terracotta'),
('minecraft:red_terracotta', 'vanilla/red_terracotta.webp', 'Red Terracotta'),
('minecraft:black_terracotta', 'vanilla/black_terracotta.webp', 'Black Terracotta'),
('minecraft:hay_block', 'vanilla/hay_block.webp', 'Hay Block'),
('minecraft:terracotta', 'vanilla/terracotta.webp', 'Terracotta'),
('minecraft:coal_block', 'vanilla/coal_block.webp', 'Coal Block'),
('minecraft:packed_ice', 'vanilla/packed_ice.webp', 'Packed ice'),
('minecraft:acacia_stairs', 'vanilla/acacia_stairs.webp', 'Acacia Stairs'),
('minecraft:dark_oak_stairs', 'vanilla/dark_oak_stairs.webp', 'Dark Oak Stairs'),
('minecraft:white_stained_glass', 'vanilla/white_stained_glass.webp', 'White Stained Glass'),
('minecraft:orange_stained_glass', 'vanilla/orange_stained_glass.webp', 'Orange Stained Glass'),
('minecraft:magenta_stained_glass', 'vanilla/magenta_stained_glass.webp', 'Magenta Stained Glass'),
('minecraft:light_blue_stained_glass', 'vanilla/light_blue_stained_glass.webp', 'Light Blue Stained Glass'),
('minecraft:yellow_stained_glass', 'vanilla/yellow_stained_glass.webp', 'Yellow Stained Glass'),
('minecraft:lime_stained_glass', 'vanilla/lime_stained_glass.webp', 'Lime Stained glass'),
('minecraft:pink_stained_glass', 'vanilla/pink_stained_glass.webp', 'Pink Stained Glass'),
('minecraft:gray_stained_glass', 'vanilla/gray_stained_glass.webp', 'Gray Stained Glass'),
('minecraft:light_gray_stained_glass', 'vanilla/light_gray_stained_glass.webp', 'Light Gray Stained Glass'),
('minecraft:cyan_stained_glass', 'vanilla/cyan_stained_glass.webp', 'Cyan Stained Glass'),
('minecraft:purple_stained_glass', 'vanilla/purple_stained_glass.webp', 'Purple Stained Glass'),
('minecraft:blue_stained_glass', 'vanilla/blue_stained_glass.webp', 'Blue Stained Glass'),
('minecraft:brown_stained_glass', 'vanilla/brown_stained_glass.webp', 'Brown Stained Glass'),
('minecraft:green_stained_glass', 'vanilla/green_stained_glass.webp', 'Green Stained Glass'),
('minecraft:red_stained_glass', 'vanilla/red_stained_glass.webp', 'Red Stained Glass'),
('minecraft:black_stained_glass', 'vanilla/black_stained_glass.webp', 'Black Stained Glass'),
('minecraft:prismarine', 'vanilla/prismarine.gif', 'Prismarine'),
('minecraft:prismarine_bricks', 'vanilla/prismarine_bricks.webp', 'Prismarine Bricks'),
('minecraft:dark_prismarine', 'vanilla/dark_prismarine.webp', 'Dark Prismarine'),
('minecraft:prismarine_stairs', 'vanilla/prismarine_stairs.webp', 'Prismarine Stairs'),
('minecraft:prismarine_brick_stairs', 'vanilla/prismarine_brick_stairs.webp', 'Prismarine Brick Stairs'),
('minecraft:dark_prismarine_stairs', 'vanilla/dark_prismarine_stairs.webp', 'Dark Prismarine Stairs'),
('minecraft:sea_lantern', 'vanilla/sea_lantern.gif', 'Sea Lantern'),
('minecraft:red_sandstone', 'vanilla/red_sandstone.webp', 'Red Sandstone'),
('minecraft:chiseled_red_sandstone', 'vanilla/chiseled_red_sandstone.webp', 'Chiseled Red Sandstone'),
('minecraft:cut_red_sandstone', 'vanilla/cut_red_sandstone.webp', 'Cut Red Sandstone'),
('minecraft:red_sandstone_stairs', 'vanilla/red_sandstone_stairs.webp', 'Red Sandstone Stairs'),
('minecraft:magma_block', 'vanilla/magma_block.webp', 'Magma Block'),
('minecraft:red_nether_bricks', 'vanilla/red_nether_bricks.webp', 'Red Nether Bricks'),
('minecraft:bone_block', 'vanilla/bone_block.webp', 'Bone Block'),
('minecraft:white_concrete', 'vanilla/white_concrete.webp', 'White Concrete'),
('minecraft:orange_concrete', 'vanilla/orange_concrete.webp', 'Orange Concrete'),
('minecraft:magenta_concrete', 'vanilla/magenta_concrete.webp', 'Magenta Concrete'),
('minecraft:light_blue_concrete', 'vanilla/light_blue_concrete.webp', 'Light Blue Concrete'),
('minecraft:yellow_concrete', 'vanilla/yellow_concrete.webp', 'Yellow Concrete'),
('minecraft:lime_concrete', 'vanilla/lime_concrete.webp', 'lime Concrete'),
('minecraft:pink_concrete', 'vanilla/pink_concrete.webp', 'Pink Concrete'),
('minecraft:gray_concrete', 'vanilla/gray_concrete.webp', 'Gray Concrete'),
('minecraft:light_gray_concrete', 'vanilla/light_gray_concrete.webp', 'Light Gray Concrete'),
('minecraft:cyan_concrete', 'vanilla/cyan_concrete.webp', 'Cyan Concrete'),
('minecraft:purple_concrete', 'vanilla/purple_concrete.webp', 'Purple Concrete'),
('minecraft:blue_concrete', 'vanilla/blue_concrete.webp', 'Blue Concrete'),
('minecraft:brown_concrete', 'vanilla/brown_concrete.webp', 'Brown Concrete'),
('minecraft:green_concrete', 'vanilla/green_concrete.webp', 'Green Concrete'),
('minecraft:red_concrete', 'vanilla/red_concrete.webp', 'Red Concrete'),
('minecraft:black_concrete', 'vanilla/black_concrete.webp', 'Black Concrete'),
('minecraft:white_concrete_powder', 'vanilla/white_concrete_powder.webp', 'White Concrete Powder'),
('minecraft:orange_concrete_powder', 'vanilla/orange_concrete_powder.webp', 'Orange Concrete Powder'),
('minecraft:magenta_concrete_powder', 'vanilla/magenta_concrete_powder.webp', 'Magenta Concrete Powder'),
('minecraft:light_blue_concrete_powder', 'vanilla/light_blue_concrete_powder.webp', 'Light Blue Concrete Powder'),
('minecraft:yellow_concrete_powder', 'vanilla/yellow_concrete_powder.webp', 'Yellow Concrete Powder'),
('minecraft:lime_concrete_powder', 'vanilla/lime_concrete_powder.webp', 'lime Concrete Powder'),
('minecraft:pink_concrete_powder', 'vanilla/pink_concrete_powder.webp', 'Pink Concrete Powder'),
('minecraft:gray_concrete_powder', 'vanilla/gray_concrete_powder.webp', 'Gray Concrete Powder'),
('minecraft:light_gray_concrete_powder', 'vanilla/light_gray_concrete_powder.webp', 'Light Gray Concrete Powder'),
('minecraft:cyan_concrete_powder', 'vanilla/cyan_concrete_powder.webp', 'Cyan Concrete Powder'),
('minecraft:purple_concrete_powder', 'vanilla/purple_concrete_powder.webp', 'Purple Concrete Powder'),
('minecraft:blue_concrete_powder', 'vanilla/blue_concrete_powder.webp', 'Blue Concrete Powder'),
('minecraft:brown_concrete_powder', 'vanilla/brown_concrete_powder.webp', 'Brown Concrete Powder'),
('minecraft:green_concrete_powder', 'vanilla/green_concrete_powder.webp', 'Green Concrete Powder'),
('minecraft:red_concrete_powder', 'vanilla/red_concrete_powder.webp', 'Red Concrete Powder'),
('minecraft:black_concrete_powder', 'vanilla/black_concrete_powder.webp', 'Black Concrete Powder'),
('minecraft:dead_tube_coral_block', 'vanilla/dead_tube_coral_block.webp', 'Dead Tube Coral Block'),
('minecraft:dead_brain_coral_block', 'vanilla/dead_brain_coral_block.webp', 'Dead Brain Coral Block'),
('minecraft:dead_bubble_coral_block', 'vanilla/dead_bubble_coral_block.webp', 'Dead Bubble Coral Block'),
('minecraft:dead_fire_coral_block', 'vanilla/dead_fire_coral_block.webp', 'Dead Fire Coral Block'),
('minecraft:dead_horn_coral_block', 'vanilla/dead_horn_coral_block.webp', 'Dead Horn Coral Block'),
('minecraft:tube_coral_block', 'vanilla/tube_coral_block.webp', 'Tube Coral Block'),
('minecraft:brain_coral_block', 'vanilla/brain_coral_block.webp', 'Brain Coral Block'),
('minecraft:bubble_coral_block', 'vanilla/bubble_coral_block.webp', 'Bubble Coral Block'),
('minecraft:fire_coral_block', 'vanilla/fire_coral_block.webp', 'Fire Coral Block'),
('minecraft:horn_coral_block', 'vanilla/horn_coral_block.webp', 'Horn Coral Block'),
('minecraft:polished_granite_stairs', 'vanilla/polished_granite_stairs.webp', 'Polished Granite Stairs'),
('minecraft:smooth_red_sandstone_stairs', 'vanilla/smooth_red_sandstone_stairs.webp', 'Smooth Red Sandstone Stairs'),
('minecraft:mossy_stone_brick_stairs', 'vanilla/mossy_stone_brick_stairs.webp', 'Mossy Stone Brick Stairs'),
('minecraft:polished_diorite_stairs', 'vanilla/polished_diorite_stairs.webp', 'Polished Diorite Stairs'),
('minecraft:mossy_cobblestone_stairs', 'vanilla/mossy_cobblestone_stairs.webp', 'Mossy Cobblestone Stairs'),
('minecraft:end_stone_brick_stairs', 'vanilla/end_stone_brick_stairs.webp', 'End Stone Brick Stairs'),
('minecraft:stone_stairs', 'vanilla/stone_stairs.webp', 'Stone Stairs'),
('minecraft:smooth_sandstone_stairs', 'vanilla/smooth_sandstone_stairs.webp', 'Smooth Sandstone Stairs'),
('minecraft:smooth_quartz_stairs', 'vanilla/smooth_quartz_stairs.webp', 'Smooth Quartz Stairs'),
('minecraft:granite_stairs', 'vanilla/granite_stairs.webp', 'Granite Stairs'),
('minecraft:andesite_stairs', 'vanilla/andesite_stairs.webp', 'Andesite Stairs'),
('minecraft:red_nether_brick_stairs', 'vanilla/red_nether_brick_stairs.webp', 'Red Nether Brick Stairs'),
('minecraft:polished_andesite_stairs', 'vanilla/polished_andesite_stairs.webp', 'Polished Andesite Stairs'),
('minecraft:diorite_stairs', 'vanilla/diorite_stairs.webp', 'Diorite Stairs'),
('minecraft:polished_granite_slab', 'vanilla/polished_granite_slab.webp', 'Polished Granite Slab'),
('minecraft:smooth_red_sandstone_slab', 'vanilla/smooth_red_sandstone_slab.webp', 'Smooth Red Sandstone Slab'),
('minecraft:mossy_stone_brick_slab', 'vanilla/mossy_stone_brick_slab.webp', 'Mossy Stone Brick Slab'),
('minecraft:polished_diorite_slab', 'vanilla/polished_diorite_slab.webp', 'Polished Diorite Slab'),
('minecraft:mossy_cobblestone_slab', 'vanilla/mossy_cobblestone_slab.webp', 'Mossy Cobbleston Slab'),
('minecraft:end_stone_brick_slab', 'vanilla/end_stone_brick_slab.webp', 'End Stone Brick Slab'),
('minecraft:smooth_sandstone_slab', 'vanilla/smooth_sandstone_slab.webp', 'Smooth Sandstone Slab'),
('minecraft:smooth_quartz_slab', 'vanilla/smooth_quartz_slab.webp', 'Smooth Quartz Slab'),
('minecraft:granite_slab', 'vanilla/granite_slab.webp', 'Granite Slab'),
('minecraft:andesite_slab', 'vanilla/andesite_slab.webp', 'Andesite Slab'),
('minecraft:red_nether_brick_slab', 'vanilla/red_nether_brick_slab.webp', 'Red nether Brick Slab'),
('minecraft:polished_andesite_slab', 'vanilla/polished_andesite_slab.webp', 'Polished Andesite Slab'),
('minecraft:diorite_slab', 'vanilla/diorite_slab.webp', 'Diorite Slab'),
('minecraft:dried_kelp_block', 'vanilla/dried_kelp_block.webp', 'Dried Kelp Block'),
('minecraft:netherite_block', 'vanilla/netherite_block.webp', 'Netherite Block'),
('minecraft:ancient_debris', 'vanilla/ancient_debris.webp', 'Ancient Debris'),
('minecraft:crying_obsidian', 'vanilla/crying_obsidian.webp', 'Crying Obsidian'),
('minecraft:blackstone', 'vanilla/blackstone.webp', 'Blackstone'),
('minecraft:blackstone_slab', 'vanilla/blackstone_slab.webp', 'Blackstone Slab'),
('minecraft:blackstone_stairs', 'vanilla/blackstone_stairs.webp', 'Blackstone Stairs'),
('minecraft:gilded_blackstone', 'vanilla/gilded_blackstone.webp', 'Gilded Blackstone'),
('minecraft:polished_blackstone', 'vanilla/polished_blackstone.webp', 'Polished Blackstone'),
('minecraft:polished_blackstone_slab', 'vanilla/polished_blackstone_slab.webp', 'Polished Blackstone Slab'),
('minecraft:polished_blackstone_stairs', 'vanilla/polished_blackstone_stairs.webp', 'Polished Blackstone Stairs'),
('minecraft:chiseled_polished_blackstone', 'vanilla/chiseled_polished_blackstone.webp', 'Chiseled Polished blackstone'),
('minecraft:polished_blackstone_bricks', 'vanilla/polished_blackstone_bricks.webp', 'Polished Blackstone Bricks'),
('minecraft:polished_blackstone_brick_slab', 'vanilla/polished_blackstone_brick_slab.webp', 'Polished Blackstone Brick Slab'),
('minecraft:polished_blackstone_brick_stairs', 'vanilla/polished_blackstone_brick_stairs.webp', 'Polished Blackstone Brick Stairs'),
('minecraft:cracked_polished_blackstone_bricks', 'vanilla/cracked_polished_blackstone_bricks.webp', 'Cracked Polished Blackstone bricks'),
('minecraft:dispenser', 'vanilla/dispenser.webp', 'Dispenser'),
('minecraft:note_block', 'vanilla/note_block.webp', 'Note Block'),
('minecraft:sticky_piston', 'vanilla/sticky_piston.webp', 'Sticky Piston'),
('minecraft:piston', 'vanilla/piston.webp', 'Piston'),
('minecraft:tnt', 'vanilla/tnt.webp', 'TNT'),
('minecraft:lever', 'vanilla/lever.webp', 'Lever'),
('minecraft:stone_pressure_plate', 'vanilla/stone_pressure_plate.webp', 'Stone Pressure Plate'),
('minecraft:oak_pressure_plate', 'vanilla/oak_pressure_plate.webp', 'Oak Pressure Plate'),
('minecraft:spruce_pressure_plate', 'vanilla/spruce_pressure_plate.webp', 'Spruce Pressure Plate'),
('minecraft:birch_pressure_plate', 'vanilla/birch_pressure_plate.webp', 'Brich Pressure Plate'),
('minecraft:jungle_pressure_plate', 'vanilla/jungle_pressure_plate.webp', 'Jungle Pressure Plate'),
('minecraft:acacia_pressure_plate', 'vanilla/acacia_pressure_plate.webp', 'Acacia  Pressure Plate'),
('minecraft:dark_oak_pressure_plate', 'vanilla/dark_oak_pressure_plate.webp', 'Dark Oak Pressure Plate'),
('minecraft:crimson_pressure_plate', 'vanilla/crimson_pressure_plate.webp', 'Crimson Pressure Plate'),
('minecraft:warped_pressure_plate', 'vanilla/warped_pressure_plate.webp', 'Warped Pressure Plate'),
('minecraft:polished_blackstone_pressure_plate', 'vanilla/polished_blackstone_pressure_plate.webp', 'Polished Blackstone Pressure Plate'),
('minecraft:redstone_torch', 'vanilla/redstone_torch.webp', 'Redstone Torch'),
('minecraft:oak_trapdoor', 'vanilla/oak_trapdoor.webp', ' Oak Trapdoor'),
('minecraft:spruce_trapdoor', 'vanilla/spruce_trapdoor.webp', 'Spruce Trapdoor'),
('minecraft:birch_trapdoor', 'vanilla/birch_trapdoor.webp', 'Birch Trapdoor'),
('minecraft:jungle_trapdoor', 'vanilla/jungle_trapdoor.webp', 'Jungle Trapdoor'),
('minecraft:acacia_trapdoor', 'vanilla/acacia_trapdoor.webp', 'Acacia Trapdoor'),
('minecraft:dark_oak_trapdoor', 'vanilla/dark_oak_trapdoor.webp', 'Dark Oak Trapdoor'),
('minecraft:crimson_trapdoor', 'vanilla/crimson_trapdoor.webp', 'Crimson Trapdoor'),
('minecraft:warped_trapdoor', 'vanilla/warped_trapdoor.webp', 'Warped Trapdoor'),
('minecraft:oak_fence_gate', 'vanilla/oak_fence_gate.webp', 'Oak Fence Gate'),
('minecraft:spruce_fence_gate', 'vanilla/spruce_fence_gate.webp', 'Spruce Fence Gate'),
('minecraft:birch_fence_gate', 'vanilla/birch_fence_gate.webp', 'Brich Fence Gate'),
('minecraft:jungle_fence_gate', 'vanilla/jungle_fence_gate.webp', 'Jungle Fence Gate'),
('minecraft:acacia_fence_gate', 'vanilla/acacia_fence_gate.webp', 'Acacia Fence Gate'),
('minecraft:dark_oak_fence_gate', 'vanilla/dark_oak_fence_gate.webp', 'Dark Oak Fence Gate'),
('minecraft:crimson_fence_gate', 'vanilla/crimson_fence_gate.webp', 'Crimson Fence Gate'),
('minecraft:warped_fence_gate', 'vanilla/warped_fence_gate.webp', 'Warped Fence Gate'),
('minecraft:redstone_lamp', 'vanilla/redstone_lamp.webp', 'Redstone Lamp'),
('minecraft:tripwire_hook', 'vanilla/tripwire_hook.webp', 'Tripwire Hook'),
('minecraft:stone_button', 'vanilla/stone_button.webp', 'Stone Button'),
('minecraft:oak_button', 'vanilla/oak_button.webp', ' Oak Button'),
('minecraft:spruce_button', 'vanilla/spruce_button.webp', 'Spruce Button'),
('minecraft:birch_button', 'vanilla/birch_button.webp', 'Birch Button'),
('minecraft:jungle_button', 'vanilla/jungle_button.webp', 'Jungle Button'),
('minecraft:acacia_button', 'vanilla/acacia_button.webp', 'Acacia Button'),
('minecraft:dark_oak_button', 'vanilla/dark_oak_button.webp', 'Dark Oak Button'),
('minecraft:crimson_button', 'vanilla/crimson_button.webp', 'Crimson Button'),
('minecraft:warped_button', 'vanilla/warped_button.webp', 'Warped Button'),
('minecraft:polished_blackstone_button', 'vanilla/polished_blackstone_button.webp', 'Polished Blackstone Button'),
('minecraft:trapped_chest', 'vanilla/trapped_chest.webp', 'Trapped Chest'),
('minecraft:light_weighted_pressure_plate', 'vanilla/light_weighted_pressure_plate.webp', 'Light Weighted Pressure Plate'),
('minecraft:heavy_weighted_pressure_plate', 'vanilla/heavy_weighted_pressure_plate.webp', 'Heavy Weighted Pressure Plate'),
('minecraft:daylight_detector', 'vanilla/daylight_detector.webp', 'Daylight Detector'),
('minecraft:redstone_block', 'vanilla/redstone_block.webp', 'Redstone Block'),
('minecraft:hopper', 'vanilla/hopper.webp', 'Hopper'),
('minecraft:dropper', 'vanilla/dropper.webp', 'Dropper'),
('minecraft:iron_trapdoor', 'vanilla/iron_trapdoor.webp', 'Iron Trapdoor'),
('minecraft:observer', 'vanilla/observer.webp', 'Observer'),
('minecraft:iron_door', 'vanilla/iron_door.webp', 'Iron Door'),
('minecraft:oak_door', 'vanilla/oak_door.webp', ' Oak Door'),
('minecraft:spruce_door', 'vanilla/spruce_door.webp', 'Spruce Door'),
('minecraft:birch_door', 'vanilla/birch_door.webp', 'Birch Door'),
('minecraft:jungle_door', 'vanilla/jungle_door.webp', 'Jungle Door'),
('minecraft:acacia_door', 'vanilla/acacia_door.webp', 'Acacia Door'),
('minecraft:dark_oak_door', 'vanilla/dark_oak_door.webp', 'Dark Oak Door'),
('minecraft:crimson_door', 'vanilla/crimson_door.webp', 'Crimson Door'),
('minecraft:warped_door', 'vanilla/warped_door.webp', 'Warped Door'),
('minecraft:repeater', 'vanilla/repeater.webp', 'Redstone Repeater'),
('minecraft:comparator', 'vanilla/comparator.webp', 'Redstone Comparator'),
('minecraft:redstone', 'vanilla/redstone.webp', 'Redstone Dust'),
('minecraft:lectern', 'vanilla/lectern.webp', 'Lectern'),
('minecraft:target', 'vanilla/target.webp', 'Target'),
('minecraft:ghast_tear', 'vanilla/ghast_tear.webp', 'Ghast Tear'),
('minecraft:fermented_spider_eye', 'vanilla/fermented_spider_eye.webp', 'Fermented Spider Eye'),
('minecraft:blaze_powder', 'vanilla/blaze_powder.webp', 'Blaze Powder'),
('minecraft:magma_cream', 'vanilla/magma_cream.webp', 'Magna Cream'),
('minecraft:brewing_stand', 'vanilla/brewing_stand.webp', 'Brewing Stand'),
('minecraft:cauldron', 'vanilla/cauldron.webp', 'Cauldron'),
('minecraft:glistering_melon_slice', 'vanilla/glistering_melon_slice.webp', 'Glistering Melon Slice'),
('minecraft:golden_carrot', 'vanilla/golden_carrot.webp', 'Golden Carrot'),
('minecraft:rabbit_foot', 'vanilla/rabbit_foot.webp', 'Rabbit Foot'),
('minecraft:dragon_breath', 'vanilla/dragon_breath.webp', 'Dragon Breath'),
('minecraft:phantom_membrane', 'vanilla/phantom_membrane.webp', 'Phantom Membrane'),
('minecraft:glass_bottle', 'vanilla/glass_bottle.webp', 'Glass Bottle'),
('minecraft:potion', 'vanilla/potion.webp', 'Potion'),
('minecraft:splash_potion', 'vanilla/splash_potion.webp', 'Splash Potion'),
('minecraft:lingering_potion', 'vanilla/lingering_potion.webp', 'Lingering Potion'),
('minecraft:beacon', 'vanilla/beacon.webp', 'Beacon'),
('minecraft:turtle_egg', 'vanilla/turtle_egg.webp', 'Turtle Egg'),
('minecraft:conduit', 'vanilla/conduit.webp', 'Conduit'),
('minecraft:scute', 'vanilla/scute.webp', 'Scute'),
('minecraft:coal', 'vanilla/coal.webp', 'Coal'),
('minecraft:charcoal', 'vanilla/charcoal.webp', 'Charcoal'),
('minecraft:diamond', 'vanilla/diamond.webp', 'Diamond'),
('minecraft:iron_ingot', 'vanilla/iron_ingot.webp', 'Iron Ingot'),
('minecraft:gold_ingot', 'vanilla/gold_ingot.webp', 'Gold Ingot'),
('minecraft:netherite_ingot', 'vanilla/netherite_ingot.webp', 'Netherite Ingot'),
('minecraft:netherite_scrap', 'vanilla/netherite_scrap.webp', 'Netherite Scrap'),
('minecraft:stick', 'vanilla/stick.webp', 'Stick'),
('minecraft:bowl', 'vanilla/bowl.webp', 'Bowl'),
('minecraft:string', 'vanilla/string.webp', 'String'),
('minecraft:feather', 'vanilla/feather.webp', 'Feather'),
('minecraft:gunpowder', 'vanilla/gunpowder.webp', 'Gunpowder'),
('minecraft:wheat_seeds', 'vanilla/wheat_seeds.webp', 'Wheat Seeds'),
('minecraft:wheat', 'vanilla/wheat.webp', 'Wheat'),
('minecraft:flint', 'vanilla/flint.webp', 'Flint'),
('minecraft:bucket', 'vanilla/bucket.webp', 'Bucket'),
('minecraft:lava_bucket', 'vanilla/lava_bucket.webp', 'Lava Bucket'),
('minecraft:water_bucket', 'vanilla/water_bucket.webp', 'Water Bucket'),
('minecraft:snowball', 'vanilla/snowball.webp', 'Snowball'),
('minecraft:leather', 'vanilla/leather.webp', 'Leather'),
('minecraft:milk_bucket', 'vanilla/milk_bucket.webp', 'Milk Bucket'),
('minecraft:pufferfish_bucket', 'vanilla/pufferfish_bucket.webp', 'Pufferfish Bucket'),
('minecraft:salmon_bucket', 'vanilla/salmon_bucket.webp', 'Salmon Bucket'),
('minecraft:cod_bucket', 'vanilla/cod_bucket.webp', 'Cod Bucket'),
('minecraft:tropical_fish_bucket', 'vanilla/tropical_fish_bucket.webp', 'Tropical Fish Bucket'),
('minecraft:brick', 'vanilla/brick.webp', 'Brick'),
('minecraft:clay_ball', 'vanilla/clay_ball.webp', 'Clay Ball'),
('minecraft:paper', 'vanilla/paper.webp', 'Paper'),
('minecraft:book', 'vanilla/book.webp', 'Book'),
('minecraft:slime_ball', 'vanilla/slime_ball.webp', 'Slime Ball'),
('minecraft:egg', 'vanilla/egg.webp', 'Egg'),
('minecraft:glowstone_dust', 'vanilla/glowstone_dust.webp', 'Glowstone'),
('minecraft:ink_sac', 'vanilla/ink_sac.webp', 'Ink Sac'),
('minecraft:red_dye', 'vanilla/red_dye.webp', 'Red Dye'),
('minecraft:green_dye', 'vanilla/green_dye.webp', 'Green Dye'),
('minecraft:cocoa_beans', 'vanilla/cocoa_beans.webp', 'Cocoa Beans'),
('minecraft:lapis_lazuli', 'vanilla/lapis_lazuli.webp', 'Lapis Lazuli'),
('minecraft:purple_dye', 'vanilla/purple_dye.webp', 'Purple Dye'),
('minecraft:cyan_dye', 'vanilla/cyan_dye.webp', 'Cyan Dye'),
('minecraft:light_gray_dye', 'vanilla/light_gray_dye.webp', 'Light Gray Dye'),
('minecraft:gray_dye', 'vanilla/gray_dye.webp', 'Gray Dye'),
('minecraft:pink_dye', 'vanilla/pink_dye.webp', 'Pink Dye'),
('minecraft:lime_dye', 'vanilla/lime_dye.webp', 'Lime Dye'),
('minecraft:yellow_dye', 'vanilla/yellow_dye.webp', 'Yellow Dye'),
('minecraft:light_blue_dye', 'vanilla/light_blue_dye.webp', 'Light Blue Dye'),
('minecraft:magenta_dye', 'vanilla/magenta_dye.webp', 'Magenta Dye'),
('minecraft:orange_dye', 'vanilla/orange_dye.webp', 'Orange Dye'),
('minecraft:bone_meal', 'vanilla/bone_meal.webp', 'Bone_meal'),
('minecraft:blue_dye', 'vanilla/blue_dye.webp', 'Blue Dye'),
('minecraft:brown_dye', 'vanilla/brown_dye.webp', 'Brown Dye'),
('minecraft:black_dye', 'vanilla/black_dye.webp', 'Black Dye'),
('minecraft:white_dye', 'vanilla/white_dye.webp', 'White Dye'),
('minecraft:bone', 'vanilla/bone.webp', 'Bone'),
('minecraft:sugar', 'vanilla/sugar.webp', 'Sugar'),
('minecraft:pumpkin_seeds', 'vanilla/pumpkin_seeds.webp', 'Pumpkin Seeds'),
('minecraft:melon_seeds', 'vanilla/melon_seeds.webp', 'Melon Seeds'),
('minecraft:ender_pearl', 'vanilla/ender_pearl.webp', 'Ender Pearl'),
('minecraft:blaze_rod', 'vanilla/blaze_rod.webp', 'Blaze Rod'),
('minecraft:gold_nugget', 'vanilla/gold_nugget.webp', 'Gold Nugget'),
('minecraft:nether_wart', 'vanilla/nether_wart.webp', 'Nether Wart'),
('minecraft:ender_eye', 'vanilla/ender_eye.webp', 'Ender_eye'),
('minecraft:bat_spawn_egg', 'vanilla/bat_spawn_egg.webp', 'Bat Spawn Egg'),
('minecraft:bee_spawn_egg', 'vanilla/bee_spawn_egg.webp', 'Bee Spawn Egg'),
('minecraft:blaze_spawn_egg', 'vanilla/blaze_spawn_egg.webp', 'Blaze Spawn Egg'),
('minecraft:cat_spawn_egg', 'vanilla/cat_spawn_egg.webp', 'Cat Spawn Egg'),
('minecraft:cave_spider_spawn_egg', 'vanilla/cave_spider_spawn_egg.webp', 'Cave Spider Spawn Egg'),
('minecraft:chicken_spawn_egg', 'vanilla/chicken_spawn_egg.webp', 'Chicken Spawn Egg'),
('minecraft:cod_spawn_egg', 'vanilla/cod_spawn_egg.webp', 'Cod Spawn Egg'),
('minecraft:cow_spawn_egg', 'vanilla/cow_spawn_egg.webp', 'Cow Spawn Egg'),
('minecraft:creeper_spawn_egg', 'vanilla/creeper_spawn_egg.webp', 'Creeper Spawn Egg'),
('minecraft:dolphin_spawn_egg', 'vanilla/dolphin_spawn_egg.webp', 'Dolphin Spawn Egg'),
('minecraft:donkey_spawn_egg', 'vanilla/donkey_spawn_egg.webp', 'Donkey Spawn Egg'),
('minecraft:drowned_spawn_egg', 'vanilla/drowned_spawn_egg.webp', 'Drowned Spawn Egg'),
('minecraft:elder_guardian_spawn_egg', 'vanilla/elder_guardian_spawn_egg.webp', 'Elder Guardian Spawn Egg'),
('minecraft:enderman_spawn_egg', 'vanilla/enderman_spawn_egg.webp', 'Enderman Spawn Egg'),
('minecraft:endermite_spawn_egg', 'vanilla/endermite_spawn_egg.webp', 'Endermite Spawn Egg'),
('minecraft:evoker_spawn_egg', 'vanilla/evoker_spawn_egg.webp', 'Evoker Spawn Egg'),
('minecraft:fox_spawn_egg', 'vanilla/fox_spawn_egg.webp', 'Fox Spawn Egg'),
('minecraft:ghast_spawn_egg', 'vanilla/ghast_spawn_egg.webp', 'Ghast Spawn Egg'),
('minecraft:guardian_spawn_egg', 'vanilla/guardian_spawn_egg.webp', 'Guardian Spawn Egg'),
('minecraft:hoglin_spawn_egg', 'vanilla/hoglin_spawn_egg.webp', 'Hoglin Spawn Egg'),
('minecraft:horse_spawn_egg', 'vanilla/horse_spawn_egg.webp', 'Horse Spawn Egg'),
('minecraft:husk_spawn_egg', 'vanilla/husk_spawn_egg.webp', 'Husk Spawn Egg'),
('minecraft:llama_spawn_egg', 'vanilla/llama_spawn_egg.webp', 'Llama Spawn Egg'),
('minecraft:magma_cube_spawn_egg', 'vanilla/magma_cube_spawn_egg.webp', 'Magma Cube Spawn Egg'),
('minecraft:mooshroom_spawn_egg', 'vanilla/mooshroom_spawn_egg.webp', 'Mooshroom Spawn Egg'),
('minecraft:mule_spawn_egg', 'vanilla/mule_spawn_egg.webp', 'Mule Spawn Egg'),
('minecraft:ocelot_spawn_egg', 'vanilla/ocelot_spawn_egg.webp', 'Ocelot Spawn Egg'),
('minecraft:panda_spawn_egg', 'vanilla/panda_spawn_egg.webp', 'Panda Spawn Egg'),
('minecraft:parrot_spawn_egg', 'vanilla/parrot_spawn_egg.webp', 'Parrot Spawn Egg'),
('minecraft:phantom_spawn_egg', 'vanilla/phantom_spawn_egg.webp', 'Phantom Spawn Egg'),
('minecraft:pig_spawn_egg', 'vanilla/pig_spawn_egg.webp', 'Pig Spawn Egg'),
('minecraft:piglin_spawn_egg', 'vanilla/piglin_spawn_egg.webp', 'Piglin Spawn Egg'),
('minecraft:pillager_spawn_egg', 'vanilla/pillager_spawn_egg.webp', 'Pillager Spawn Egg'),
('minecraft:polar_bear_spawn_egg', 'vanilla/polar_bear_spawn_egg.webp', 'Polar Bear Spawn Egg'),
('minecraft:pufferfish_spawn_egg', 'vanilla/pufferfish_spawn_egg.webp', 'Pufferfish Spawn Egg'),
('minecraft:rabbit_spawn_egg', 'vanilla/rabbit_spawn_egg.webp', 'Rabbit Spawn Egg'),
('minecraft:ravager_spawn_egg', 'vanilla/ravager_spawn_egg.webp', 'Ravager Spawn Egg'),
('minecraft:salmon_spawn_egg', 'vanilla/salmon_spawn_egg.webp', 'Salmon Spawn Egg'),
('minecraft:sheep_spawn_egg', 'vanilla/sheep_spawn_egg.webp', 'Sheep Spawn Egg'),
('minecraft:shulker_spawn_egg', 'vanilla/shulker_spawn_egg.webp', 'Shulker Spawn Egg'),
('minecraft:silverfish_spawn_egg', 'vanilla/silverfish_spawn_egg.webp', 'Silverfish Spawn Egg'),
('minecraft:skeleton_spawn_egg', 'vanilla/skeleton_spawn_egg.webp', 'Skeleton Spawn Egg'),
('minecraft:skeleton_horse_spawn_egg', 'vanilla/skeleton_horse_spawn_egg.webp', 'Skeleton Horse Spawn Egg'),
('minecraft:slime_spawn_egg', 'vanilla/slime_spawn_egg.webp', 'Slime Spawn Egg'),
('minecraft:spider_spawn_egg', 'vanilla/spider_spawn_egg.webp', 'Spider Spawn Egg'),
('minecraft:squid_spawn_egg', 'vanilla/squid_spawn_egg.webp', 'Squid Spawn Egg'),
('minecraft:stray_spawn_egg', 'vanilla/stray_spawn_egg.webp', 'Stray Spawn Egg'),
('minecraft:strider_spawn_egg', 'vanilla/strider_spawn_egg.webp', 'Strider Spawn Egg'),
('minecraft:trader_llama_spawn_egg', 'vanilla/trader_llama_spawn_egg.webp', 'Trader Llama Spawn Egg'),
('minecraft:tropical_fish_spawn_egg', 'vanilla/tropical_fish_spawn_egg.webp', 'Tropical Fish Spawn Egg'),
('minecraft:turtle_spawn_egg', 'vanilla/turtle_spawn_egg.webp', 'Turtle Spawn Egg'),
('minecraft:vex_spawn_egg', 'vanilla/vex_spawn_egg.webp', 'Vex Spawn Egg'),
('minecraft:villager_spawn_egg', 'vanilla/villager_spawn_egg.webp', 'Villager Spawn Egg'),
('minecraft:vindicator_spawn_egg', 'vanilla/vindicator_spawn_egg.webp', 'Vindicator Spawn Egg'),
('minecraft:wandering_trader_spawn_egg', 'vanilla/wandering_trader_spawn_egg.webp', 'Wandering Trader Spawn Egg'),
('minecraft:witch_spawn_egg', 'vanilla/witch_spawn_egg.webp', 'Witch Spawn Egg'),
('minecraft:wither_skeleton_spawn_egg', 'vanilla/wither_skeleton_spawn_egg.webp', 'Wither Skeleton Spawn Egg'),
('minecraft:wolf_spawn_egg', 'vanilla/wolf_spawn_egg.webp', 'Wolf Spawn Egg'),
('minecraft:zoglin_spawn_egg', 'vanilla/zoglin_spawn_egg.webp', 'Zoglin Spawn Egg'),
('minecraft:zombie_spawn_egg', 'vanilla/zombie_spawn_egg.webp', 'Zombie Spawn Egg'),
('minecraft:zombie_horse_spawn_egg', 'vanilla/zombie_horse_spawn_egg.webp', 'Zombie Horse Spawn Egg'),
('minecraft:zombified_piglin_spawn_egg', 'vanilla/zombified_piglin_spawn_egg.webp', 'Zombified Piglin Spawn Egg'),
('minecraft:zombie_villager_spawn_egg', 'vanilla/zombie_villager_spawn_egg.webp', 'Zombie Villager Spawn Egg'),
('minecraft:experience_bottle', 'vanilla/experience_bottle.gif', 'Experience Bottle'),
('minecraft:fire_charge', 'vanilla/fire_charge.webp', 'Fire Charge'),
('minecraft:writable_book', 'vanilla/book_and_quill.webp', 'Book And Quill'),
('minecraft:emerald', 'vanilla/emerald.webp', 'Emerald'),
('minecraft:map', 'vanilla/map.webp', 'Map'),
('minecraft:nether_star', 'vanilla/nether_star.webp', 'Nether Star'),
('minecraft:firework_rocket', 'vanilla/firework_rocket.webp', 'Firework Rocket'),
('minecraft:firework_star', 'vanilla/firework_star.webp', 'Firework Star'),
('minecraft:nether_brick', 'vanilla/nether_brick.webp', 'Nether Brick'),
('minecraft:quartz', 'vanilla/quartz.webp', 'Quartz'),
('minecraft:prismarine_shard', 'vanilla/prismarine_shard.webp', 'Prismarine Shard'),
('minecraft:prismarine_crystals', 'vanilla/prismarine_crystals.webp', 'Prismarine Crystals'),
('minecraft:rabbit_hide', 'vanilla/rabbit_hide.webp', 'Rabbit Hide'),
('minecraft:iron_horse_armor', 'vanilla/iron_horse_armor.webp', 'Iron Horse Armor'),
('minecraft:golden_horse_armor', 'vanilla/golden_horse_armor.webp', 'Golden Horse Armor'),
('minecraft:diamond_horse_armor', 'vanilla/diamond_horse_armor.webp', 'Diamond Horse Armor'),
('minecraft:leather_horse_armor', 'vanilla/leather_horse_armor.webp', 'Leather Horse Armor'),
('minecraft:chorus_fruit', 'vanilla/chorus_fruit.webp', 'Chorus Fruit'),
('minecraft:popped_chorus_fruit', 'vanilla/popped_chorus_fruit.webp', 'Popped Chorus Fruit'),
('minecraft:beetroot_seeds', 'vanilla/beetroot_seeds.webp', 'Beetroot Seeds'),
('minecraft:shulker_shell', 'vanilla/shulker_shell.webp', 'Shulker Shell'),
('minecraft:iron_nugget', 'vanilla/iron_nugget.webp', 'Iron Nugget'),
('minecraft:music_disc_13', 'vanilla/music_disc_13.webp', 'Music Disc 13'),
('minecraft:music_disc_cat', 'vanilla/music_disc_cat.webp', 'Music Disc cat'),
('minecraft:music_disc_blocks', 'vanilla/music_disc_blocks.webp', 'Music Disc blocks'),
('minecraft:music_disc_chirp', 'vanilla/music_disc_chirp.webp', 'Music Disc chirp'),
('minecraft:music_disc_far', 'vanilla/music_disc_far.webp', 'Music Disc far'),
('minecraft:music_disc_mall', 'vanilla/music_disc_mall.webp', 'Music Disc mall'),
('minecraft:music_disc_mellohi', 'vanilla/music_disc_mellohi.webp', 'Music Disc mellosi'),
('minecraft:music_disc_stal', 'vanilla/music_disc_stal.webp', 'Music Disc stal'),
('minecraft:music_disc_strad', 'vanilla/music_disc_strad.webp', 'Music Disc strad'),
('minecraft:music_disc_ward', 'vanilla/music_disc_ward.webp', 'Music Disc ward'),
('minecraft:music_disc_11', 'vanilla/music_disc_11.webp', 'Music Disc 11'),
('minecraft:music_disc_wait', 'vanilla/music_disc_wait.webp', 'Music Disc wait'),
('minecraft:music_disc_pigstep', 'vanilla/music_disc_pigstep.webp', 'Music Disc pigstep'),
('minecraft:nautilus_shell', 'vanilla/nautilus_shell.webp', 'Nautilus_shell'),
('minecraft:heart_of_the_sea', 'vanilla/heart_of_the_sea.webp', 'Heart Of The Sea'),
('minecraft:flower_banner_pattern', 'vanilla/flower_banner_pattern.webp', 'Flower Banner Pattern'),
('minecraft:creeper_banner_pattern', 'vanilla/creeper_banner_pattern.webp', 'Creeper Banner Pattern'),
('minecraft:skull_banner_pattern', 'vanilla/skull_banner_pattern.webp', 'Skull Banner Pattern'),
('minecraft:mojang_banner_pattern', 'vanilla/mojang_banner_pattern.webp', 'Mojang Banner Pattern'),
('minecraft:globe_banner_pattern', 'vanilla/globe_banner_pattern.webp', 'Globe Banner Pattern'),
('minecraft:piglin_banner_pattern', 'vanilla/piglin_banner_pattern.webp', 'Piglin Banner Pattern'),
('minecraft:honeycomb', 'vanilla/honeycomb.webp', 'Honeycomb'),
('minecraft:oak_sapling', 'vanilla/oak_sapling.webp', 'Oak Sapling'),
('minecraft:spruce_sapling', 'vanilla/spruce_sapling.webp', 'Spruce Sapling'),
('minecraft:birch_sapling', 'vanilla/birch_sapling.webp', 'Birch Sapling'),
('minecraft:jungle_sapling', 'vanilla/jungle_sapling.webp', 'Jungle Sapling'),
('minecraft:acacia_sapling', 'vanilla/acacia_sapling.webp', 'Acacia Sapling'),
('minecraft:dark_oak_sapling', 'vanilla/dark_oak_sapling.webp', 'Dark Oak Sapling'),
('minecraft:oak_leaves', 'vanilla/oak_leaves.webp', 'Oak Leaves'),
('minecraft:spruce_leaves', 'vanilla/spruce_leaves.webp', 'Spruce Leaves'),
('minecraft:birch_leaves', 'vanilla/birch_leaves.webp', 'Birch Leaves'),
('minecraft:jungle_leaves', 'vanilla/jungle_leaves.webp', 'Jungle Leaves'),
('minecraft:acacia_leaves', 'vanilla/acacia_leaves.webp', 'Acacia Leaves'),
('minecraft:dark_oak_leaves', 'vanilla/dark_oak_leaves.webp', 'Dark Oak Leaves'),
('minecraft:cobweb', 'vanilla/cobweb.webp', 'Cobweb'),
('minecraft:grass', 'vanilla/grass.webp', 'Grass'),
('minecraft:fern', 'vanilla/fern.webp', 'Fern'),
('minecraft:dead_bush', 'vanilla/dead_bush.webp', 'Dead Bush'),
('minecraft:seagrass', 'vanilla/seagrass.webp', 'Seagrass'),
('minecraft:sea_pickle', 'vanilla/sea_pickle.webp', 'Sea Pickle'),
('minecraft:dandelion', 'vanilla/dandelion.webp', 'Dandelion'),
('minecraft:poppy', 'vanilla/poppy.webp', 'Poppy'),
('minecraft:blue_orchid', 'vanilla/blue_orchid.webp', 'Blue Orchid'),
('minecraft:allium', 'vanilla/allium.webp', 'Allium'),
('minecraft:azure_bluet', 'vanilla/azure_bluet.webp', 'Azure Bluet'),
('minecraft:red_tulip', 'vanilla/red_tulip.webp', 'Red Tulip'),
('minecraft:orange_tulip', 'vanilla/orange_tulip.webp', 'Orange Tulip'),
('minecraft:white_tulip', 'vanilla/white_tulip.webp', 'White Tulip'),
('minecraft:pink_tulip', 'vanilla/pink_tulip.webp', 'Pink Tulip'),
('minecraft:oxeye_daisy', 'vanilla/oxeye_daisy.webp', 'Oxeye_daisy'),
('minecraft:cornflower', 'vanilla/cornflower.webp', 'Cornflower'),
('minecraft:lily_of_the_valley', 'vanilla/lily_of_the_valley.webp', 'Lily Of The Valley'),
('minecraft:wither_rose', 'vanilla/wither_rose.webp', 'Wither Rose'),
('minecraft:brown_mushroom', 'vanilla/brown_mushroom.webp', 'Brown Mushroom'),
('minecraft:red_mushroom', 'vanilla/red_mushroom.webp', 'Red Mushroom'),
('minecraft:crimson_fungus', 'vanilla/crimson_fungus.webp', 'Crimson Fungus'),
('minecraft:warped_fungus', 'vanilla/warped_fungus.webp', 'Warped Fungus'),
('minecraft:crimson_roots', 'vanilla/crimson_roots.webp', 'Crimson Roots'),
('minecraft:warped_roots', 'vanilla/warped_roots.webp', 'Warped Roots'),
('minecraft:nether_sprouts', 'vanilla/nether_sprouts.webp', 'Nether Sprouts'),
('minecraft:weeping_wines', 'vanilla/weeping_vines.webp', 'Weeping Wines'),
('minecraft:twisting_vines', 'vanilla/twisting_vines.webp', 'Twisting Wines'),
('minecraft:sugar_cane', 'vanilla/sugar_cane.webp', 'Sugar Cane'),
('minecraft:kelp', 'vanilla/kelp.webp', 'Kelp'),
('minecraft:bamboo', 'vanilla/bamboo.webp', 'Bamboo'),
('minecraft:torch', 'vanilla/torch.webp', 'Torch'),
('minecraft:end_rod', 'vanilla/end_rod.webp', 'End Rod'),
('minecraft:chorus_plant', 'vanilla/chorus_plant.webp', 'Chorus Plant'),
('minecraft:chorus_flower', 'vanilla/chorus_flower.webp', 'Chorus Flower'),
('minecraft:chest', 'vanilla/chest.webp', 'Chest'),
('minecraft:crafting_table', 'vanilla/crafting_table.webp', 'Crafting Table'),
('minecraft:farmland', 'vanilla/farmland.webp', 'Farmland'),
('minecraft:furnace', 'vanilla/furnace.webp', 'Furnace'),
('minecraft:ladder', 'vanilla/ladder.webp', 'Ladder'),
('minecraft:snow', 'vanilla/snow.webp', 'Snow'),
('minecraft:cactus', 'vanilla/cactus.webp', 'Cactus'),
('minecraft:jukebox', 'vanilla/jukebox.webp', 'Jukebox'),
('minecraft:oak_fence', 'vanilla/oak_fence.webp', 'Oak Fence'),
('minecraft:spruce_fence', 'vanilla/spruce_fence.webp', 'Spruce Fence'),
('minecraft:birch_fence', 'vanilla/birch_fence.webp', 'Birch Fence'),
('minecraft:jungle_fence', 'vanilla/jungle_fence.webp', 'Jungle Fence'),
('minecraft:acacia_fence', 'vanilla/acacia_fence.webp', 'Acacia Fence'),
('minecraft:dark_oak_fence', 'vanilla/dark_oak_fence.webp', 'Dark Oak Fence'),
('minecraft:crimson_fence', 'vanilla/crimson_fence.webp', 'Crimson Fence'),
('minecraft:warped_fence', 'vanilla/warped_fence.webp', 'Warped Fence'),
('minecraft:soul_torch', 'vanilla/soul_torch.webp', 'Soul Torch'),
('minecraft:infested_stone', 'vanilla/infested_stone.webp', 'Infested Stone'),
('minecraft:infested_cobblestone', 'vanilla/infested_cobblestone.webp', 'Infested Cobblestone'),
('minecraft:infested_stone_bricks', 'vanilla/infested_stone_bricks.webp', 'Infested Stone Bricks'),
('minecraft:infested_mossy_stone_bricks', 'vanilla/infested_mossy_stone_bricks.webp', 'Infested Mossy Stone Bricks'),
('minecraft:infested_cracked_stone_bricks', 'vanilla/infested_cracked_stone_bricks.webp', 'Infested Cracked Stone Bricks'),
('minecraft:infested_chiseled_stone_bricks', 'vanilla/infested_chiseled_stone_bricks.webp', 'Infested Chiseled Stone Bricks'),
('minecraft:brown_mushroom_block', 'vanilla/brown_mushroom_block.webp', 'Brown Mushroom Block'),
('minecraft:red_mushroom_block', 'vanilla/red_mushroom_block.webp', 'Red Mushroom Block'),
('minecraft:mushroom_stem', 'vanilla/mushroom_stem.webp', 'Mushroom Stem'),
('minecraft:iron_bars', 'vanilla/iron_bars.webp', 'Iron Bars'),
('minecraft:chain', 'vanilla/chain.webp', 'Chain'),
('minecraft:glass_pane', 'vanilla/glass_pane.webp', 'Glass Pane'),
('minecraft:vine', 'vanilla/vine.webp', 'Vine'),
('minecraft:lily_pad', 'vanilla/lily_pad.webp', 'Lily Pad'),
('minecraft:nether_brick_fence', 'vanilla/nether_brick_fence.webp', 'Nether Brick Fence'),
('minecraft:enchanting_table', 'vanilla/enchanting_table.webp', 'Enchanting Table'),
('minecraft:end_portal_frame', 'vanilla/end_portal_frame.webp', 'End_portal Frame'),
('minecraft:ender_chest', 'vanilla/ender_chest.webp', 'Ender Chest'),
('minecraft:cobblestone_wall', 'vanilla/cobblestone_wall.webp', 'Cobblestone Wall'),
('minecraft:mossy_cobblestone_wall', 'vanilla/mossy_cobblestone_wall.webp', 'Mossy Cobblestone Wall'),
('minecraft:brick_wall', 'vanilla/brick_wall.webp', 'Brick Wall'),
('minecraft:prismarine_wall', 'vanilla/prismarine_wall.webp', 'Prismarine Wall'),
('minecraft:red_sandstone_wall', 'vanilla/red_sandstone_wall.webp', 'Red Sandstone Wall'),
('minecraft:mossy_stone_brick_wall', 'vanilla/mossy_stone_brick_wall.webp', 'Mossy Stone Brick Wall'),
('minecraft:granite_wall', 'vanilla/granite_wall.webp', 'Granite Wall'),
('minecraft:stone_brick_wall', 'vanilla/stone_brick_wall.webp', 'Stone Brick Wall'),
('minecraft:nether_brick_wall', 'vanilla/nether_brick_wall.webp', 'Nether Brick Wall'),
('minecraft:andesite_wall', 'vanilla/andesite_wall.webp', 'Andesite Wall'),
('minecraft:red_nether_brick_wall', 'vanilla/red_nether_brick_wall.webp', 'Red Nether Brick Wall'),
('minecraft:sandstone_wall', 'vanilla/sandstone_wall.webp', 'Sandstone Wall'),
('minecraft:end_stone_brick_wall', 'vanilla/end_stone_brick_wall.webp', 'End Stone Brick Wall'),
('minecraft:diorite_wall', 'vanilla/diorite_wall.webp', 'Diorite Wall'),
('minecraft:blackstone_wall', 'vanilla/blackstone_wall.webp', 'Blackstone Wall'),
('minecraft:polished_blackstone_wall', 'vanilla/polished_blackstone_wall.webp', 'Polished Blackstone Wall'),
('minecraft:polished_blackstone_brick_wall', 'vanilla/polished_blackstone_brick_wall.webp', 'Polished Blackstone Brick Wall'),
('minecraft:anvil', 'vanilla/anvil.webp', 'Anvil'),
('minecraft:chipped_anvil', 'vanilla/chipped_anvil.webp', 'Chipped Anvil'),
('minecraft:damaged_anvil', 'vanilla/damaged_anvil.webp', 'Damaged Anvil'),
('minecraft:white_carpet', 'vanilla/white_carpet.webp', 'White Carpet'),
('minecraft:orange_carpet', 'vanilla/orange_carpet.webp', 'Orange Carpet'),
('minecraft:magenta_carpet', 'vanilla/magenta_carpet.webp', 'Magenta Carpet'),
('minecraft:light_blue_carpet', 'vanilla/light_blue_carpet.webp', 'Light Blue Carpet'),
('minecraft:yellow_carpet', 'vanilla/yellow_carpet.webp', 'Yellow Carpet'),
('minecraft:lime_carpet', 'vanilla/lime_carpet.webp', 'Lime Carpet'),
('minecraft:pink_carpet', 'vanilla/pink_carpet.webp', 'Pink Carpet'),
('minecraft:gray_carpet', 'vanilla/gray_carpet.webp', 'Gray Carpet'),
('minecraft:light_gray_carpet', 'vanilla/light_gray_carpet.webp', 'Light Gray Carpet'),
('minecraft:cyan_carpet', 'vanilla/cyan_carpet.webp', 'Cyan Carpet'),
('minecraft:purple_carpet', 'vanilla/purple_carpet.webp', 'Purple Carpet'),
('minecraft:blue_carpet', 'vanilla/blue_carpet.webp', 'Blue Carpet'),
('minecraft:brown_carpet', 'vanilla/brown_carpet.webp', 'Brown Carpet'),
('minecraft:green_carpet', 'vanilla/green_carpet.webp', 'Green Carpet'),
('minecraft:red_carpet', 'vanilla/red_carpet.webp', 'Red Carpet'),
('minecraft:black_carpet', 'vanilla/black_carpet.webp', 'Black Carpet'),
('minecraft:slime_block', 'vanilla/slime_block.webp', 'Slime Block'),
('minecraft:grass_path', 'vanilla/grass_path.webp', 'Grass Path'),
('minecraft:sunflower', 'vanilla/sunflower.webp', 'Sunflower'),
('minecraft:lilac', 'vanilla/lilac.webp', 'Lilac'),
('minecraft:rose_bush', 'vanilla/rose_bush.webp', 'Rose Bush'),
('minecraft:peony', 'vanilla/peony.webp', 'Peony'),
('minecraft:tall_grass', 'vanilla/tall_grass.webp', 'Tall Grass'),
('minecraft:large_fern', 'vanilla/large_fern.webp', 'Large Fern'),
('minecraft:white_stained_glass_pane', 'vanilla/white_stained_glass_pane.webp', 'White Stained Glass Pane'),
('minecraft:orange_stained_glass_pane', 'vanilla/orange_stained_glass_pane.webp', 'Orange Stained Glass Pane'),
('minecraft:magenta_stained_glass_pane', 'vanilla/magenta_stained_glass_pane.webp', 'Magenta Stained Glass Pane'),
('minecraft:light_blue_stained_glass_pane', 'vanilla/light_blue_stained_glass_pane.webp', 'Light Blue Stained Glass Pane'),
('minecraft:yellow_stained_glass_pane', 'vanilla/yellow_stained_glass_pane.webp', 'Yellow Stained Glass Pane'),
('minecraft:lime_stained_glass_pane', 'vanilla/lime_stained_glass_pane.webp', 'Lime Stained Glass Pane'),
('minecraft:pink_stained_glass_pane', 'vanilla/pink_stained_glass_pane.webp', 'Pink Stained Glass Pane'),
('minecraft:gray_stained_glass_pane', 'vanilla/gray_stained_glass_pane.webp', 'Gray Stained Glass Pane'),
('minecraft:light_gray_stained_glass_pane', 'vanilla/light_gray_stained_glass_pane.webp', 'Light Gray Stained Glass Pane'),
('minecraft:cyan_stained_glass_pane', 'vanilla/cyan_stained_glass_pane.webp', 'Cyan Stained Glass Pane'),
('minecraft:purple_stained_glass_pane', 'vanilla/purple_stained_glass_pane.webp', 'Purple Stained Glass Pane'),
('minecraft:blue_stained_glass_pane', 'vanilla/blue_stained_glass_pane.webp', 'Blue Stained Glass Pane'),
('minecraft:brown_stained_glass_pane', 'vanilla/brown_stained_glass_pane.webp', 'Brown Stained Glass Pane'),
('minecraft:green_stained_glass_pane', 'vanilla/green_stained_glass_pane.webp', 'Green Stained Glass Pane'),
('minecraft:red_stained_glass_pane', 'vanilla/red_stained_glass_pane.webp', 'Red Stained Glass Pane'),
('minecraft:black_stained_glass_pane', 'vanilla/black_stained_glass_pane.webp', 'Black Stained Glass Pane'),
('minecraft:shulker_box', 'vanilla/shulker_box.webp', 'Shulker Box'),
('minecraft:white_shulker_box', 'vanilla/white_shulker_box.webp', 'White Shulker Box'),
('minecraft:orange_shulker_box', 'vanilla/orange_shulker_box.webp', 'Orange Shulker Box'),
('minecraft:magenta_shulker_box', 'vanilla/magenta_shulker_box.webp', 'Magenta Shulker Box'),
('minecraft:light_blue_shulker_box', 'vanilla/light_blue_shulker_box.webp', 'Light Blue Shulker Box'),
('minecraft:yellow_shulker_box', 'vanilla/yellow_shulker_box.webp', 'Yellow Shulker Box'),
('minecraft:lime_shulker_box', 'vanilla/lime_shulker_box.webp', 'Lime Shulker Box'),
('minecraft:pink_shulker_box', 'vanilla/pink_shulker_box.webp', 'Pink Shulker Box'),
('minecraft:gray_shulker_box', 'vanilla/gray_shulker_box.webp', 'Gray Shulker Box'),
('minecraft:light_gray_shulker_box', 'vanilla/light_gray_shulker_box.webp', 'Light Gray Shulker Box'),
('minecraft:cyan_shulker_box', 'vanilla/cyan_shulker_box.webp', 'Cyan Shulker Box'),
('minecraft:purple_shulker_box', 'vanilla/purple_shulker_box.webp', 'Purple Shulker Box'),
('minecraft:blue_shulker_box', 'vanilla/blue_shulker_box.webp', 'Blue Shulker Box'),
('minecraft:brown_shulker_box', 'vanilla/brown_shulker_box.webp', 'Brown Shulker Box'),
('minecraft:green_shulker_box', 'vanilla/green_shulker_box.webp', 'Green Shulker Box'),
('minecraft:red_shulker_box', 'vanilla/red_shulker_box.webp', 'Red Shulker Box'),
('minecraft:black_shulker_box', 'vanilla/black_shulker_box.webp', 'Black Shulker Box'),
('minecraft:white_glazed_terracotta', 'vanilla/white_glazed_terracotta.webp', 'White Glazed Terracotta'),
('minecraft:orange_glazed_terracotta', 'vanilla/orange_glazed_terracotta.webp', 'Orange Glazed Terracotta'),
('minecraft:magenta_glazed_terracotta', 'vanilla/magenta_glazed_terracotta.webp', 'Magenta Glazed Terracotta'),
('minecraft:light_blue_glazed_terracotta', 'vanilla/light_blue_glazed_terracotta.webp', 'Light Blue Glazed Terracotta'),
('minecraft:yellow_glazed_terracotta', 'vanilla/yellow_glazed_terracotta.webp', 'Yellow Glazed Terracotta'),
('minecraft:lime_glazed_terracotta', 'vanilla/lime_glazed_terracotta.webp', 'Lime Glazed Terracotta'),
('minecraft:pink_glazed_terracotta', 'vanilla/pink_glazed_terracotta.webp', 'Pink Glazed Terracotta'),
('minecraft:gray_glazed_terracotta', 'vanilla/gray_glazed_terracotta.webp', 'Gray Glazed Terracotta'),
('minecraft:light_gray_glazed_terracotta', 'vanilla/light_gray_glazed_terracotta.webp', 'Light Gray Glazed Terracotta'),
('minecraft:cyan_glazed_terracotta', 'vanilla/cyan_glazed_terracotta.webp', 'Cyan Glazed Terracotta'),
('minecraft:purple_glazed_terracotta', 'vanilla/purple_glazed_terracotta.webp', 'Purple Glazed Terracotta'),
('minecraft:blue_glazed_terracotta', 'vanilla/blue_glazed_terracotta.webp', 'Blue Glazed Terracotta'),
('minecraft:brown_glazed_terracotta', 'vanilla/brown_glazed_terracotta.webp', 'Brown Glazed Terracotta'),
('minecraft:green_glazed_terracotta', 'vanilla/green_glazed_terracotta.webp', 'Green Glazed Terracotta'),
('minecraft:red_glazed_terracotta', 'vanilla/red_glazed_terracotta.webp', 'Red Glazed Terracotta'),
('minecraft:black_glazed_terracotta', 'vanilla/black_glazed_terracotta.webp', 'Black Glazed Terracotta'),
('minecraft:tube_coral', 'vanilla/tube_coral.webp', 'Tube Coral'),
('minecraft:brain_coral', 'vanilla/brain_coral.webp', 'Brain Coral'),
('minecraft:bubble_coral', 'vanilla/bubble_coral.webp', 'Bubble Coral'),
('minecraft:fire_coral', 'vanilla/fire_coral.webp', 'Fire Coral'),
('minecraft:horn_coral', 'vanilla/horn_coral.webp', 'Horn Coral'),
('minecraft:dead_tube_coral', 'vanilla/dead_tube_coral.webp', 'Dead Tube Coral'),
('minecraft:dead_brain_coral', 'vanilla/dead_brain_coral.webp', 'Dead Brain Coral'),
('minecraft:dead_bubble_coral', 'vanilla/dead_bubble_coral.webp', 'Dead Bubble Coral'),
('minecraft:dead_fire_coral', 'vanilla/dead_fire_coral.webp', 'Dead Fire Coral'),
('minecraft:dead_horn_coral', 'vanilla/dead_horn_coral.webp', 'Dead Horn Coral'),
('minecraft:tube_coral_fan', 'vanilla/tube_coral_fan.webp', 'Tube CoralF an'),
('minecraft:brain_coral_fan', 'vanilla/brain_coral_fan.webp', 'Brain Coral Fan'),
('minecraft:bubble_coral_fan', 'vanilla/bubble_coral_fan.webp', 'Bubble Coral Fan'),
('minecraft:fire_coral_fan', 'vanilla/fire_coral_fan.webp', 'Fire Coral Fan'),
('minecraft:horn_coral_fan', 'vanilla/horn_coral_fan.webp', 'Horn Coral Fan'),
('minecraft:dead_tube_coral_fan', 'vanilla/dead_tube_coral_fan.webp', 'Dead Tube Coral Fan'),
('minecraft:dead_brain_coral_fan', 'vanilla/dead_brain_coral_fan.webp', 'Dead Brain Coral Fan'),
('minecraft:dead_bubble_coral_fan', 'vanilla/dead_bubble_coral_fan.webp', 'Dead Bubble Coral Fan'),
('minecraft:dead_fire_coral_fan', 'vanilla/dead_fire_coral_fan.webp', 'Dead Fire_Coral Fan'),
('minecraft:dead_horn_coral_fan', 'vanilla/dead_horn_coral_fan.webp', 'Dead Horn Coral Fan'),
('minecraft:scaffolding', 'vanilla/scaffolding.webp', 'Scaffolding'),
('minecraft:painting', 'vanilla/painting.webp', 'Painting'),
('minecraft:oak_sign', 'vanilla/oak_sign.webp', 'Oak Sign'),
('minecraft:spruce_sign', 'vanilla/spruce_sign.webp', 'Spruce Sign'),
('minecraft:birch_sign', 'vanilla/birch_sign.webp', 'Birch Sign'),
('minecraft:jungle_sign', 'vanilla/jungle_sign.webp', 'Jungle Sign'),
('minecraft:acacia_sign', 'vanilla/acacia_sign.webp', 'Acacia Sign'),
('minecraft:dark_oak_sign', 'vanilla/dark_oak_sign.webp', 'Dark Oak Sign'),
('minecraft:crimson_sign', 'vanilla/crimson_sign.webp', 'Crimson Sign'),
('minecraft:warped_sign', 'vanilla/warped_sign.webp', 'Warped Sign'),
('minecraft:white_bed', 'vanilla/white_bed.webp', 'White Bed'),
('minecraft:orange_bed', 'vanilla/orange_bed.webp', 'Orange Bed'),
('minecraft:magenta_bed', 'vanilla/magenta_bed.webp', 'Magenta  Bed'),
('minecraft:light_blue_bed', 'vanilla/light_blue_bed.webp', 'Light Blue Bed'),
('minecraft:yellow_bed', 'vanilla/yellow_bed.webp', 'Yellow Bed'),
('minecraft:lime_bed', 'vanilla/lime_bed.webp', 'Lime Bed'),
('minecraft:pink_bed', 'vanilla/pink_bed.webp', 'Pink Bed'),
('minecraft:gray_bed', 'vanilla/gray_bed.webp', 'Gray Bed'),
('minecraft:light_gray_bed', 'vanilla/light_gray_bed.webp', 'Light Gray Bed'),
('minecraft:cyan_bed', 'vanilla/cyan_bed.webp', 'Cyan Bed'),
('minecraft:purple_bed', 'vanilla/purple_bed.webp', 'Purple Bed'),
('minecraft:blue_bed', 'vanilla/blue_bed.webp', 'Blue Bed'),
('minecraft:brown_bed', 'vanilla/brown_bed.webp', 'Brown Bed'),
('minecraft:green_bed', 'vanilla/green_bed.webp', 'Green Bed'),
('minecraft:red_bed', 'vanilla/red_bed.webp', 'Red Bed'),
('minecraft:black_bed', 'vanilla/black_bed.webp', 'Black Bed'),
('minecraft:item_frame', 'vanilla/item_frame.webp', 'Item Frame'),
('minecraft:flower_pot', 'vanilla/flower_pot.webp', 'Flower Pot'),
('minecraft:skeleton_skull', 'vanilla/skeleton_skull.webp', 'Skeleton Skull'),
('minecraft:wither_skeleton_skull', 'vanilla/wither_skeleton_skull.webp', 'Wither Skeleton Skull'),
('minecraft:player_head', 'vanilla/player_head.webp', 'Player Head'),
('minecraft:zombie_head', 'vanilla/zombie_head.webp', 'Zombie Head'),
('minecraft:creeper_head', 'vanilla/creeper_head.webp', 'Creeper Head'),
('minecraft:dragon_head', 'vanilla/dragon_head.webp', 'Dragon Head'),
('minecraft:armor_stand', 'vanilla/armor_stand.webp', 'Armor_stand'),
('minecraft:white_banner', 'vanilla/white_banner.webp', 'White Banner'),
('minecraft:orange_banner', 'vanilla/orange_banner.webp', 'Orange Banner'),
('minecraft:magenta_banner', 'vanilla/magenta_banner.webp', 'Magenta Banner'),
('minecraft:light_blue_banner', 'vanilla/light_blue_banner.webp', 'Light Blue Banner'),
('minecraft:yellow_banner', 'vanilla/yellow_banner.webp', 'Yellow Banner'),
('minecraft:lime_banner', 'vanilla/lime_banner.webp', 'Lime Banner'),
('minecraft:pink_banner', 'vanilla/pink_banner.webp', 'Pink Banner'),
('minecraft:gray_banner', 'vanilla/gray_banner.webp', 'Gray Banner'),
('minecraft:light_gray_banner', 'vanilla/light_gray_banner.webp', 'Light Gray Banner'),
('minecraft:cyan_banner', 'vanilla/cyan_banner.webp', 'Cyan Banner'),
('minecraft:purple_banner', 'vanilla/purple_banner.webp', 'Purple Banner'),
('minecraft:blue_banner', 'vanilla/blue_banner.webp', 'Blue Banner'),
('minecraft:brown_banner', 'vanilla/brown_banner.webp', 'Brown Banner'),
('minecraft:green_banner', 'vanilla/green_banner.webp', 'Green Banner'),
('minecraft:red_banner', 'vanilla/red_banner.webp', 'Red Banner'),
('minecraft:black_banner', 'vanilla/black_banner.webp', 'Black Banner'),
('minecraft:end_crystal', 'vanilla/end_crystal.webp', 'EndC rystal'),
('minecraft:loom', 'vanilla/loom.webp', 'Loom'),
('minecraft:composter', 'vanilla/composter.webp', 'Composter'),
('minecraft:barrel', 'vanilla/barrel.webp', 'Barrel'),
('minecraft:smoker', 'vanilla/smoker.webp', 'Smoker'),
('minecraft:blast_furnace', 'vanilla/blast_furnace.webp', 'Blast Furnace'),
('minecraft:cartography_table', 'vanilla/cartography_table.webp', 'Cartography Table'),
('minecraft:fletching_table', 'vanilla/fletching_table.webp', 'Fletching Table'),
('minecraft:grindstone', 'vanilla/grindstone.webp', 'Grindstone'),
('minecraft:smithing_table', 'vanilla/smithing_table.webp', 'Smithing Table'),
('minecraft:stonecutter', 'vanilla/stonecutter.gif', 'Stonecutter'),
('minecraft:bell', 'vanilla/bell.webp', 'Bell'),
('minecraft:lantern', 'vanilla/lantern.webp', 'Lantern'),
('minecraft:soul_lantern', 'vanilla/soul_lantern.webp', 'Soul Lantern'),
('minecraft:campfire', 'vanilla/campfire.webp', 'Camp Fire'),
('minecraft:soul_campfire', 'vanilla/soul_campfire.webp', 'Soul Campfire'),
('minecraft:shroomlight', 'vanilla/shroomlight.webp', 'Shroomlight'),
('minecraft:bee_nest', 'vanilla/bee_nest.webp', 'Bee Nest'),
('minecraft:beehive', 'vanilla/beehive.webp', 'Beehive'),
('minecraft:honey_block', 'vanilla/honey_block.webp', 'Honey Block'),
('minecraft:honeycomb_block', 'vanilla/honeycomb_block.webp', 'Honeycomb Block'),
('minecraft:lodestone', 'vanilla/lodestone.webp', 'Lodestone'),
('minecraft:respawn_anchor', 'vanilla/respawn_anchor.webp', 'Respawn Anchor'),
('minecraft:turtle_helmet', 'vanilla/turtle_helmet.webp', 'Turtle Helmet'),
('minecraft:bow', 'vanilla/bow.webp', 'Bow'),
('minecraft:arrow', 'vanilla/arrow.webp', 'Arrow'),
('minecraft:iron_sword', 'vanilla/iron_sword.webp', 'Iron Sword'),
('minecraft:wooden_sword', 'vanilla/wooden_sword.webp', 'Wooden Sword'),
('minecraft:stone_sword', 'vanilla/stone_sword.webp', 'Stone Sword'),
('minecraft:diamond_sword', 'vanilla/diamond_sword.webp', 'Diamond Sword'),
('minecraft:golden_sword', 'vanilla/golden_sword.webp', 'Golden Sword'),
('minecraft:netherite_sword', 'vanilla/netherite_sword.webp', 'Netherite Sword'),
('minecraft:leather_helmet', 'vanilla/leather_helmet.webp', 'Leather Helmet'),
('minecraft:leather_chestplate', 'vanilla/leather_chestplate.webp', 'Leather Chestplate'),
('minecraft:leather_leggings', 'vanilla/leather_leggings.webp', 'Leather Leggings'),
('minecraft:leather_boots', 'vanilla/leather_boots.webp', 'Leather Boots'),
('minecraft:iron_helmet', 'vanilla/iron_helmet.webp', 'Iron Helmet'),
('minecraft:iron_chestplate', 'vanilla/iron_chestplate.webp', 'Iron Chestplate'),
('minecraft:iron_leggings', 'vanilla/iron_leggings.webp', 'Iron Leggings'),
('minecraft:iron_boots', 'vanilla/iron_boots.webp', 'Iron Boots'),
('minecraft:chainmail_helmet', 'vanilla/chainmail_helmet.webp', 'Chainmail Helmet'),
('minecraft:chainmail_chestplate', 'vanilla/chainmail_chestplate.webp', 'Chainmail Chestplate'),
('minecraft:chainmail_leggings', 'vanilla/chainmail_leggings.webp', 'Chainmail Leggings'),
('minecraft:chainmail_boots', 'vanilla/chainmail_boots.webp', 'Chainmail Boots'),
('minecraft:diamond_helmet', 'vanilla/diamond_helmet.webp', 'Diamond Helmet'),
('minecraft:diamond_chestplate', 'vanilla/diamond_chestplate.webp', 'Diamond Chestplate'),
('minecraft:diamond_leggings', 'vanilla/diamond_leggings.webp', 'Diamond Leggings'),
('minecraft:diamond_boots', 'vanilla/diamond_boots.webp', 'Diamond Boots'),
('minecraft:golden_helmet', 'vanilla/golden_helmet.webp', 'Golden Helmet'),
('minecraft:golden_chestplate', 'vanilla/golden_chestplate.webp', 'Golden Chestplate'),
('minecraft:golden_leggings', 'vanilla/golden_leggings.webp', 'Golden Leggings'),
('minecraft:golden_boots', 'vanilla/golden_boots.webp', 'Golden Boots'),
('minecraft:netherite_helmet', 'vanilla/netherite_helmet.webp', 'Netherite Helmet'),
('minecraft:netherite_chestplate', 'vanilla/netherite_chestplate.webp', 'Netherite Chestplate'),
('minecraft:netherite_leggings', 'vanilla/netherite_leggings.webp', 'Netherite Leggings'),
('minecraft:netherite_boots', 'vanilla/netherite_boots.webp', 'Netherite Boots'),
('minecraft:enchanted_book', 'vanilla/enchanted_book.gif', 'Enchanted Book'),
('minecraft:spectral_arrow', 'vanilla/spectral_arrow.webp', 'Spectral Arrow'),
('minecraft:tipped_arrow', 'vanilla/tipped_arrow.webp', 'Tipped Arrow'),
('minecraft:shield', 'vanilla/shield.webp', 'Shield'),
('minecraft:totem_of_undying', 'vanilla/totem_of_undying.webp', 'Totem Of Undying'),
('minecraft:trident', 'vanilla/trident.webp', 'Trident'),
('minecraft:crossbow', 'vanilla/crossbow_standby.webp', 'Crossbow'),
('minecraft:iron_shovel', 'vanilla/iron_shovel.webp', 'Iron Shovel'),
('minecraft:iron_pickaxe', 'vanilla/iron_pickaxe.webp', 'Iron Pickaxe'),
('minecraft:iron_axe', 'vanilla/iron_axe.webp', 'Iron Axe'),
('minecraft:flint_and_steel', 'vanilla/flint_and_steel.webp', 'Flint and Steel'),
('minecraft:wooden_shovel', 'vanilla/wooden_shovel.webp', 'Wooden Shovel'),
('minecraft:wooden_pickaxe', 'vanilla/wooden_pickaxe.webp', 'Wooden Pickaxe'),
('minecraft:wooden_axe', 'vanilla/wooden_axe.webp', 'Wooden Axe'),
('minecraft:stone_shovel', 'vanilla/stone_shovel.webp', 'Stone Shovel'),
('minecraft:stone_pickaxe', 'vanilla/stone_pickaxe.webp', 'Stone Pickaxe'),
('minecraft:stone_axe', 'vanilla/stone_axe.webp', 'Stone Axe'),
('minecraft:diamond_shovel', 'vanilla/diamond_shovel.webp', 'Diamond Shovel'),
('minecraft:diamond_pickaxe', 'vanilla/diamond_pickaxe.webp', 'Diamond Pickaxe'),
('minecraft:diamond_axe', 'vanilla/diamond_axe.webp', 'Diamond Axe'),
('minecraft:golden_shovel', 'vanilla/golden_shovel.webp', 'Golden Shovel'),
('minecraft:golden_pickaxe', 'vanilla/golden_pickaxe.webp', 'Golden Pickaxe'),
('minecraft:golden_axe', 'vanilla/golden_axe.webp', 'Golden Axe'),
('minecraft:netherite_shovel', 'vanilla/netherite_shovel.webp', 'Netherite Shovel'),
('minecraft:netherite_pickaxe', 'vanilla/netherite_pickaxe.webp', 'Netherite Pickaxe'),
('minecraft:netherite_axe', 'vanilla/netherite_axe.webp', 'Netherite Axe'),
('minecraft:wooden_hoe', 'vanilla/wooden_hoe.webp', 'Wooden Hoe'),
('minecraft:stone_hoe', 'vanilla/stone_hoe.webp', 'Stone Hoe'),
('minecraft:iron_hoe', 'vanilla/iron_hoe.webp', 'Iron Hoe'),
('minecraft:diamond_hoe', 'vanilla/diamond_hoe.webp', 'Diamond Hoe'),
('minecraft:golden_hoe', 'vanilla/golden_hoe.webp', 'Golden Hoe'),
('minecraft:netherite_hoe', 'vanilla/netherite_hoe.webp', 'Netherite Hoe'),
('minecraft:compass', 'vanilla/compass_00.webp', 'Compass'),
('minecraft:fishing_rod', 'vanilla/fishing_rod.webp', 'Fishing Rod'),
('minecraft:clock', 'vanilla/clock_00.webp', 'Clock'),
('minecraft:shears', 'vanilla/shears.webp', 'Shears'),
('minecraft:enchanted_book', 'vanilla/enchanted_book.gif', 'Enchanted Book'),
('minecraft:lead', 'vanilla/lead.webp', 'Lead'),
('minecraft:name_tag', 'vanilla/name_tag.webp', 'Name Tag'),
('minecraft:apple', 'vanilla/apple.webp', 'Apple'),
('minecraft:mushroom_stew', 'vanilla/mushroom_stew.webp', 'Mushroom Stew'),
('minecraft:bread', 'vanilla/bread.webp', 'Bread'),
('minecraft:porkchop', 'vanilla/porkchop.webp', 'Porkchop'),
('minecraft:cooked_porkchop', 'vanilla/cooked_porkchop.webp', 'Cooked Porkchop'),
('minecraft:golden_apple', 'vanilla/golden_apple.webp', 'Golden Apple'),
('minecraft:enchanted_golden_apple', 'vanilla/enchanted_golden_apple.webp', 'Enchanted Golden Apple'),
('minecraft:cod', 'vanilla/cod.webp', 'Cod'),
('minecraft:salmon', 'vanilla/salmon.webp', 'Salmon'),
('minecraft:tropical_fish', 'vanilla/tropical_fish.webp', 'Tropical Fish'),
('minecraft:pufferfish', 'vanilla/pufferfish.webp', 'Pufferfish'),
('minecraft:cooked_cod', 'vanilla/cooked_cod.webp', 'Cooked Cod'),
('minecraft:cooked_salmon', 'vanilla/cooked_salmon.webp', 'Cooked Salmon'),
('minecraft:cake', 'vanilla/cake.webp', 'Cake'),
('minecraft:cookie', 'vanilla/cookie.webp', 'Cookie'),
('minecraft:melon_slice', 'vanilla/melon_slice.webp', 'Melon Slice'),
('minecraft:dried_kelp', 'vanilla/dried_kelp.webp', 'Dried Kelp'),
('minecraft:beef', 'vanilla/beef.webp', 'Beef'),
('minecraft:cooked_beef', 'vanilla/cooked_beef.webp', 'Cooked Beef'),
('minecraft:chicken', 'vanilla/chicken.webp', 'Chicken'),
('minecraft:cooked_chicken', 'vanilla/cooked_chicken.webp', 'Cooked Chicken'),
('minecraft:rotten_flesh', 'vanilla/rotten_flesh.webp', 'Rotten Flesh'),
('minecraft:spider_eye', 'vanilla/spider_eye.webp', 'Spider Eye'),
('minecraft:carrot', 'vanilla/carrot.webp', 'Carrot'),
('minecraft:potato', 'vanilla/potato.webp', 'Potato'),
('minecraft:baked_potato', 'vanilla/baked_potato.webp', 'Baked Potato'),
('minecraft:poisonous_potato', 'vanilla/poisonous_potato.webp', 'Poisonous Potato'),
('minecraft:pumpkin_pie', 'vanilla/pumpkin_pie.webp', 'Pumpkin Pie'),
('minecraft:rabbit', 'vanilla/rabbit.webp', 'Rabbit'),
('minecraft:cooked_rabbit', 'vanilla/cooked_rabbit.webp', 'Cooked Rabbit'),
('minecraft:rabbit_stew', 'vanilla/rabbit_stew.webp', 'Rabbit Stew'),
('minecraft:mutton', 'vanilla/mutton.webp', 'Mutton'),
('minecraft:cooked_mutton', 'vanilla/cooked_mutton.webp', 'Cooked Mutton'),
('minecraft:beetroot', 'vanilla/beetroot.webp', 'Beetroot'),
('minecraft:beetroot_soup', 'vanilla/beetroot_soup.webp', 'Beetroot Soup'),
('minecraft:sweet_berries', 'vanilla/sweet_berries.webp', 'Sweet Berries'),
('minecraft:honey_bottle', 'vanilla/honey_bottle.webp', 'Honey Bottle'),
('minecraft:powered_rail', 'vanilla/powered_rail.gif', 'Powered Rail'),
('minecraft:detector_rail', 'vanilla/detector_rail.gif', 'Detector Rail'),
('minecraft:rail', 'vanilla/rail.webp', 'Rail'),
('minecraft:activator_rail', 'vanilla/activator_rail.gif', 'Activator Rail'),
('minecraft:saddle', 'vanilla/saddle.webp', 'Saddle'),
('minecraft:minecart', 'vanilla/minecart.webp', 'Minecart'),
('minecraft:chest_minecart', 'vanilla/chest_minecart.webp', 'Minecart with Chest'),
('minecraft:furnace_minecart', 'vanilla/furnace_minecart.webp', 'Minecart with Furnace'),
('minecraft:carrot_on_a_stick', 'vanilla/carrot_on_a_stick.webp', 'Carrot on a Stick'),
('minecraft:warped_fungus_on_a_stick', 'vanilla/warped_fungus_on_a_stick.webp', 'Warped Fungus on a Stick'),
('minecraft:tnt_minecart', 'vanilla/tnt_minecart.webp', 'Minecart with TNT'),
('minecraft:hopper_minecart', 'vanilla/hopper_minecart.webp', 'Menecart with Hopper'),
('minecraft:elytra', 'vanilla/elytra.webp', 'Elytra'),
('minecraft:oak_boat', 'vanilla/oak_boat.webp', 'Oak Boat'),
('minecraft:spruce_boat', 'vanilla/spruce_boat.webp', 'Spruce Boat'),
('minecraft:birch_boat', 'vanilla/birch_boat.webp', 'Birch Boat'),
('minecraft:jungle_boat', 'vanilla/jungle_boat.webp', 'Jungle Boat'),
('minecraft:acacia_boat', 'vanilla/acacia_boat.webp', 'Acacia Boat'),
('minecraft:dark_oak_boat', 'vanilla/dark_oak_boat.webp', 'Dark Oak Boat'),
('minecraft:barrier', 'vanilla/barrier.webp', 'Barrier'),
('minecraft:command_block', 'vanilla/command_block.webp', 'Command Block'),
('minecraft:chain_command_block', 'vanilla/chain_command_block.webp', 'Chain Command Block'),
('minecraft:repeat_command_block', 'vanilla/repeat_command_block.webp', 'Repeat Command Block'),
('minecraft:debug_stick', 'vanilla/debug_stick.webp', 'Debug Stick'),
('minecraft:minecart_with_command_block', 'vanilla/minecart_with_command_block.webp', 'Minecart With Command Blokc'),
('minecraft:mob_spawner', 'vanilla/mob_spawner.webp', 'Monster Spawner'),
('minecraft:structure_block', 'vanilla/structure_block.webp', 'Structure Block'),
('minecraft:structure_void', 'vanilla/structure_void.webp', 'Structure Void'),
('minecraft:dragon_egg', 'vanilla/dragon_egg.webp', 'Dragon Egg'),
('minecraft:knowledge_book', 'vanilla/knowledge_book.webp', 'Knowledge Book'),
('minecraft:jigsaw', 'vanilla/jigsaw.webp', 'Jigsaw Block'),
('minecraft:suspicious_stew', 'vanilla/suspicious_stew.webp', 'Suspicious Stew'),
('minecraft:stripped_oak_wood', 'vanilla/stripped_oak_wood.webp', 'Stripped Oak Wood'),
('minecraft:stripped_spruce_wood', 'vanilla/stripped_spruce_wood.webp', 'Stripped Spruce Wood'),
('minecraft:stripped_birch_wood', 'vanilla/stripped_birch_wood.webp', 'Stripped Birch Wood'),
('minecraft:stripped_jungle_wood', 'vanilla/stripped_jungle_wood.webp', 'Stripped Jungle Wood'),
('minecraft:stripped_dark_oak_wood', 'vanilla/stripped_dark_oak_wood.webp', 'Stripped Dark Oak Wood'),
('minecraft:stripped_acacia_wood', 'vanilla/stripped_acacia_wood.webp', 'Stripped Acacia Wood'),
('minecraft:stripped_warped_hyphae', 'vanilla/stripped_warped_hyphae.webp', 'Stripped Warped Hyphae'),
('minecraft:stripped_crimson_hyphae', 'vanilla/stripped_crimson_hyphae.webp', 'Stripped Crimson Hyphae'),
('minecraft:nether_wart_block', 'vanilla/nether_wart_block.webp', 'Nether Wart_Block'),
('minecraft:warped_wart_block', 'vanilla/warped_wart_block.webp', 'Warped Wart Block'),
('minecraft:purpur_stairs', 'vanilla/purpur_stairs.webp', 'Purpur Stairs'),
('minecraft:purpur_block', 'vanilla/purpur_block.webp', 'Purpur Block'),
('minecraft:written_book', 'vanilla/written_book.webp', 'Written Book'),
('minecraft:blue_ice', 'vanilla/blue_ice.webp', 'Blue Ice'),
('minecraft:amethyst_geode_block', 'vanilla/amethyst_geode_block.webp', 'Amethyst Geode Block'),
('minecraft:budding_amethyst', 'vanilla/budding_amethyst.webp', 'Budding Amethyst'),
('minecraft:calcite', 'vanilla/calcite.webp', 'Calcite'),
('minecraft:tuff', 'vanilla/tuff.webp', 'Tuff'),
('minecraft:tinted_glass', 'vanilla/tinted_glass.webp', 'Tinted Glass'),
('minecraft:copper_ore', 'vanilla/copper_ore.webp', 'Copper Ore'),
('minecraft:copper_block', 'vanilla/copper_block.webp', 'Copper Block'),
('minecraft:cut_copper', 'vanilla/cut_copper.webp', 'Cut Copper'),
('minecraft:cut_copper_slab', 'vanilla/cut_copper_slab.webp', 'Cut Copper Slab'),
('minecraft:cut_copper_stairs', 'vanilla/cut_copper_stairs.webp', 'Cut Copper Stairs'),
('minecraft:lightly_weathered_copper_block', 'vanilla/lightly_weathered_copper_block.webp', 'Lightly Weathered Copper Block'),
('minecraft:lightly_weathered_cut_copper', 'vanilla/lightly_weathered_cut_copper.webp', 'Lightly Weathered Cut Copper'),
('minecraft:lightly_weathered_cut_copper_slab', 'vanilla/lightly_weathered_cut_copper_slab.webp', 'Lightly Weathered Cut Copper Slab'),
('minecraft:lightly_weathered_cut_copper_stairs', 'vanilla/lightly_weathered_cut_copper_stairs.webp', 'Lightly Weathered Cut Copper Stairs'),
('minecraft:semi_weathered_copper_block', 'vanilla/semi-weathered_copper_block.webp', 'Semi Weathered Copper Block'),
('minecraft:semi_weathered_cut_copper', 'vanilla/semi-weathered_cut_copper.webp', 'Semi Weathered Cut Copper'),
('minecraft:semi_weathered_cut_copper_slab', 'vanilla/semi-weathered_cut_copper_slab.webp', 'Semi Weathered Cut_Copper Slab'),
('minecraft:semi_weathered_cut_copper_stairs', 'vanilla/semi-weathered_cut_copper_stairs.webp', 'Semi Weathere Cut Copper Stairs'),
('minecraft:weathered_copper_block', 'vanilla/weathered_copper_block.webp', 'Weathered Copper Block'),
('minecraft:weathered_cut_copper', 'vanilla/weathered_cut_copper.webp', 'Weathered Cut Copper'),
('minecraft:weathered_cut_copper_slab', 'vanilla/weathered_cut_copper_slab.webp', 'Weathered Cut Copper Slab'),
('minecraft:weathered_cut_copper_stairs', 'vanilla/weathered_cut_copper_stairs.webp', 'Weathered Cut Copper Stairs'),
('minecraft:candle', 'vanilla/candle.webp', 'Candle'),
('minecraft:white_candle', 'vanilla/white_candle.webp', 'White Candle'),
('minecraft:orange_candle', 'vanilla/orange_candle.webp', 'Orange Candle'),
('minecraft:magenta_candle', 'vanilla/magenta_candle.webp', 'Magenta Candle'),
('minecraft:light_blue_candle', 'vanilla/light_blue_candle.webp', 'Light Blue Candle'),
('minecraft:yellow_candle', 'vanilla/yellow_candle.webp', 'Yellow Candle'),
('minecraft:lime_candle', 'vanilla/lime_candle.webp', 'Lime Candle'),
('minecraft:pink_candle', 'vanilla/pink_candle.webp', 'Pink Candle'),
('minecraft:gray_candle', 'vanilla/gray_candle.webp', 'Gray Candle'),
('minecraft:light_gray_candle', 'vanilla/light_gray_candle.webp', 'Light Gray Candle'),
('minecraft:cyan_candle', 'vanilla/cyan_candle.webp', 'Cyan Candle'),
('minecraft:purple_candle', 'vanilla/purple_candle.webp', 'Purple Candle'),
('minecraft:blue_candle', 'vanilla/blue_candle.webp', 'Blue Candle'),
('minecraft:brown_candle', 'vanilla/brown_candle.webp', 'Brown Candle'),
('minecraft:green_candle', 'vanilla/green_candle.webp', 'Green Candle'),
('minecraft:red_candle', 'vanilla/red_candle.webp', 'Red Candle'),
('minecraft:black_candle', 'vanilla/black_candle.webp', 'Black Candle'),
('minecraft:small_amethyst_rud', 'vanilla/small_amethyst_rud.webp', 'Small Amethyst Rud'),
('minecraft:medium_amethyst_bud', 'vanilla/medium_amethyst_bud.webp', 'Medium Amethyst Bud'),
('minecraft:large_amethyst_bud', 'vanilla/large_amethyst_bud.webp', 'Large Amethyst Bud'),
('minecraft:amethyst_cluster', 'vanilla/amethyst_cluster.webp', 'Amethyst Cluster'),
('minecraft:amethyst_shard', 'vanilla/amethyst_shard.webp', 'Amethyst Shard'),
('minecraft:spyglass', 'vanilla/spyglass.webp', 'Spyglass'),
('minecraft:lightning_rod', 'vanilla/lightning_rod.webp', 'Lightning Rod'),
('minecraft:bundle', 'vanilla/bundle.webp', 'Bundle'),
('minecraft:waxed_copper_block', 'vanilla/copper_block.webp', 'Waxed Copper Block'),
('minecraft:waxed_cut_copper', 'vanilla/cut_copper.webp', 'Waxed Cut Copper'),
('minecraft:waxed_cut_copper_slab', 'vanilla/cut_copper_slab.webp', 'Waxed Cut Copper Slab'),
('minecraft:waxed_cut_copper_stairs', 'vanilla/cut_copper_stairs.webp', 'Waxed Cut Copper Stairs'),
('minecraft:waxed_lightly_weathered_copper_block', 'vanilla/lightly_weathered_copper_block.webp', 'Waxed Lightly Weathered Copper Block'),
('minecraft:waxed_lightly_weathered_cut_copper', 'vanilla/lightly_weathered_cut_copper.webp', 'Waxed Lightly Weathered Cut Copper'),
('minecraft:waxed_lightly_weathered_cut_copper_slab', 'vanilla/lightly_weathered_cut_copper_slab.webp', 'Waxed Lightly Weathered Cut Copper Slab'),
('minecraft:waxed_lightly_weathered_cut_copper_stairs', 'vanilla/lightly_weathered_cut_copper_stairs.webp', 'Waxed Lightly Weathered Cut Copper Stairs'),
('minecraft:waxed_semi_weathered_copper_block', 'vanilla/semi-weathered_copper_block.webp', 'Waxed Semi Weathered Copper Block'),
('minecraft:waxed_semi_weathered_cut_copper', 'vanilla/semi-weathered_cut_copper.webp', 'Waxed Semi Weathered Cut Copper'),
('minecraft:waxed_semi_weathered_cut_copper_slab', 'vanilla/semi-weathered_cut_copper_slab.webp', 'Waxed Semi Weathered Cut_Copper Slab'),
('minecraft:waxed_semi_weathered_cut_copper_stairs', 'vanilla/semi-weathered_cut_copper_stairs.webp', 'Waxed Semi Weathere Cut Copper Stairs'),
('minecraft:powder_snow_bucket', 'vanilla/powder_snow_bucket.webp', 'Powder Snow Bucket'),
('minecraft:copper_ingot', 'vanilla/copper_ingot.webp', 'Copper Ingot');